import Vue from 'vue'
import Router from 'vue-router'
import store from '@/store/index'
import {AUTH_REAUTH_REQUEST} from '@/store/modules/general/auth'

Vue.use(Router)

export const autenticado = (to, from, next) => {
  if (store.getters.isAuthenticated) {
    next()
  } else {
    store.commit(AUTH_REAUTH_REQUEST, true)
    next()
  }
}

export default new Router({
  mode: 'history',
  routes: [
    {
      path: '/',
      name: 'Dashboard',
      component: () => import('@/components/DashBoard')
    },
    {
      path: '/main',
      components: {
        default: () => import('@/components/Home'),
        terceros: () => import('@/components/administrativo/niif/terceros/Terceros'),
        afiliados: () => import('@/components/misional/aseguramiento/afiliados/Afiliados'),
        detalleGeneralAfiliado: () => import('@/components/misional/aseguramiento/afiliados/DetalleGeneralAfiliado'),
        pagadores: () => import('@/components/misional/aseguramiento/pagadores/Pagadores'),
        registroTercero: () => import('@/components/administrativo/niif/terceros/RegistroTercero'),
        registroAfiliado: () => import('@/components/misional/aseguramiento/afiliados/RegistroAfiliado'),
        registroPagador: () => import('@/components/misional/aseguramiento/pagadores/RegistroPagador'),
        portabilidad: () => import('@/components/misional/aseguramiento/portabilidad/Portabilidad'),
        registroPortabilidad: () => import('@/components/misional/aseguramiento/portabilidad/RegistroPortabilidad'),
        aprobacionPortabilidad: () => import('@/components/misional/aseguramiento/portabilidad/AprobacionPortabilidad'),
        detallePortabilidad: () => import('@/components/misional/aseguramiento/portabilidad/DetallePortabilidad'),
        home: () => import('@/components/Home'),
        // Configuración NiiF
        configuracionNiif: () => import('@/components/administrativo/niif/ConfiguracionNiif'),
        centrosCosto: () => import('@/components/administrativo/niif/CentrosCosto'),
        tiposComdiario: () => import('@/components/administrativo/niif/TiposComdiario'),
        conRtfs: () => import('@/components/administrativo/niif/conceptoRtf/ConRtfs'),
        registroRtf: () => import('@/components/administrativo/niif/conceptoRtf/RegistroRtf'),
        comdiarios: () => import('@/components/administrativo/niif/comprobanteDiario/ComDiarios'),
        registroComdiario: () => import('@/components/administrativo/niif/comprobanteDiario/RegistroComdiario'),
        repetirComprobanteDiario: () => import('@/components/administrativo/niif/RepetirComprobanteDiario/RepetirComprobanteDiario'),
        cierreAperturaMes: () => import('@/components/administrativo/niif/CierreAperturaMes/RegistroCierreAperturaMes'),
        contabilidadInterfazContable: () => import('@/components/administrativo/niif/contabilidadInterfazContable/ContabilidadInterfazContable'),
        // // Configuración PUC
        niifs: () => import('@/components/administrativo/niif/puc/Puc'),
        registroNiif: () => import('@/components/administrativo/niif/puc/RegistroNiif'),
        configuracionPuc: () => import('@/components/administrativo/niif/puc/Configuracion'),
        anexosDeclaracion: () => import('@/components/administrativo/niif/puc/AnexosDeclaracion'),
        clasesCuenta: () => import('@/components/administrativo/niif/puc/ClasesCuenta'),
        nivelesCuenta: () => import('@/components/administrativo/niif/puc/NivelesCuenta'),
        // // pagos
        configuracionPagos: () => import('@/components/administrativo/pagos/ConfiguracionPagos'),
        conPagos: () => import('@/components/administrativo/pagos/ConPagos'),
        unidadesApoyo: () => import('@/components/administrativo/pagos/UnidadesApoyo'),
        pg_proveedores: () => import('@/components/administrativo/pagos/Proveedores'),
        registroProveedor: () => import('@/components/administrativo/pagos/RegistroProveedor'),
        cxps: () => import('@/components/administrativo/pagos/Cxps'),
        registroCxp: () => import('@/components/administrativo/pagos/RegistroCxp'),
        salIniciales: () => import('@/components/administrativo/pagos/saldosIniciales/SalIniciales'),
        registroSalInicial: () => import('@/components/administrativo/pagos/saldosIniciales/RegistroSalInicial'),
        anticipos: () => import('@/components/administrativo/pagos/Anticipos'),
        cruceAnticipos: () => import('@/components/administrativo/pagos/CruceAnticipos'),
        // // tesoreria
        bancos: () => import('@/components/administrativo/tesoreria/Bancos'),
        cajas: () => import('@/components/administrativo/tesoreria/Cajas'),
        cuentasBancarias: () => import('@/components/administrativo/tesoreria/cuentasBancarias/CuentasBancarias'),
        registroCuentaBancaria: () => import('@/components/administrativo/tesoreria/cuentasBancarias/RegistroCuentaBancaria'),
        conceptosTesoreria: () => import('@/components/administrativo/tesoreria/Conceptos/Conceptos'),
        conceptosTesoreriaRegistro: () => import('@/components/administrativo/tesoreria/Conceptos/RegistroConcepto'),
        parametrosTesoreria: () => import('@/components/administrativo/tesoreria/Parametros'),
        reciboscaja: () => import('@/components/administrativo/tesoreria/RecibosCaja/RecibosCaja'),
        registroRecibosCaja: () => import('@/components/administrativo/tesoreria/RecibosCaja/RegistroRecibosCaja'),
        comprobantesegresos: () => import('@/components/administrativo/tesoreria/ComprobantesEgreso/ComprobantesEgresos'),
        registroComprobantesEgresos: () => import('@/components/administrativo/tesoreria/ComprobantesEgreso/RegistroComprobantesEgresos'),
        comprobantesnotas: () => import('@/components/administrativo/tesoreria/ComprobantesNotas/ComprobantesNotas'),
        registroComprobantesNotas: () => import('@/components/administrativo/tesoreria/ComprobantesNotas/RegistroComprobantesNotas'),
        // // Aseguramiento
        procesosBDUA: () => import('@/components/misional/aseguramiento/bdua/procesos/ProcesosBDUA'),
        registroProcesoBDUA: () => import('@/components/misional/aseguramiento/bdua/procesos/RegistroProcesoBDUA'),
        respuestasBDUA: () => import('@/components/misional/aseguramiento/bdua/respuestas/RespuestasBDUA'),
        respuestas: () => import('@/components/misional/aseguramiento/bdua/respuestas/Respuestas'),
        detalleRespuestas: () => import('@/components/misional/aseguramiento/bdua/respuestas/DetalleRespuestas'),
        depuracionBDUA: () => import('@/components/misional/aseguramiento/bdua/depuraciones/DepuracionBDUA'),
        registroDepuracionBDUA: () => import('@/components/misional/aseguramiento/bdua/depuraciones/RegistroDepuracionBDUA'),
        registroMS: () => import('@/components/misional/aseguramiento/bdua/depuraciones/RegistroMS'),
        cajasCompensacionFamiliar: () => import('@/components/misional/aseguramiento/cajasCompensacionFamiliar/CajasCompensacionFamiliar'),
        aseguradorasRiesgosLaborales: () => import('@/components/misional/aseguramiento/aseguradorasRiesgosLaborales/AseguradorasRiesgosLaborales'),
        adminsFondosPensiones: () => import('@/components/misional/aseguramiento/adminsFondosPensiones/AdminsFondosPensiones'),
        eps: () => import('@/components/misional/aseguramiento/eps/Eps'),
        altocostos: () => import('@/components/misional/aseguramiento/altocostos/Altocosto'),
        cargaRecaudos: () => import('@/components/misional/aseguramiento/recaudos/CargaRecaudo'),
        // // otros
        cxcs: () => import('@/components/administrativo/cartera/CuentasPorCobrar/CuentasPorCobrar'),
        registroCxc: () => import('@/components/administrativo/cartera/CuentasPorCobrar/RegistroCuentaPorCobrar'),
        conceptosCartera: () => import('@/components/administrativo/cartera/ConceptosCartera/ConceptosCartera'),
        registroConceptosCartera: () => import('@/components/administrativo/cartera/ConceptosCartera/RegistrarConceptos'),
        cliente: () => import('@/components/administrativo/cartera/clientes/Clientes'),
        registroCliente: () => import('@/components/administrativo/cartera/clientes/RegistroCliente'),
        vendedores: () => import('@/components/administrativo/cartera/vendedores/Vendedores'),
        saliniciales: () => import('@/components/administrativo/cartera/SaldosIniciales/SaldosIniciales'),
        registroSaldIniciales: () => import('@/components/administrativo/cartera/SaldosIniciales/RegistroSaldosIniciales'),
        configuracionCartera: () => import('@/components/administrativo/cartera/Configuracion'),
        notasdebito: () => import('@/components/administrativo/cartera/NotasDebito/NotasDebito'),
        registroNotasDebito: () => import('@/components/administrativo/cartera/NotasDebito/RegistroNotasDebito'),
        notascredito: () => import('@/components/administrativo/cartera/NotasCredito/NotasCredito'),
        registroNotasCredito: () => import('@/components/administrativo/cartera/NotasCredito/RegistroNotasCredito'),
        tramitesAfiliacion: () => import('@/components/misional/aseguramiento/tramites/afiliaciones/Afiliaciones'),
        registroAfiliacion: () => import('@/components/misional/aseguramiento/tramites/afiliaciones/RegistroAfiliacion'),
        tramitesNovedad: () => import('@/components/misional/aseguramiento/tramites/novedades/Novedades'),
        registroNovedad: () => import('@/components/misional/aseguramiento/tramites/novedades/RegistroNovedad'),
        tramitesTraslado: () => import('@/components/misional/aseguramiento/tramites/traslados/Traslados'),
        registroTraslado: () => import('@/components/misional/aseguramiento/tramites/traslados/RegistroTraslado'),
        tramitesSolTraslado: () => import('@/components/misional/aseguramiento/tramites/soltraslados/SolTraslados'),
        empresa: () => import('@/components/administrativo/generales/Empresa'),
        usuarios: () => import('@/components/general/seguridad/usuarios/Usuario'),
        registroUsuario: () => import('@/components/general/seguridad/usuarios/RegistroUsuario'),
        roles: () => import('@/components/general/seguridad/roles/Roles'),
        barrios: () => import('@/components/administrativo/generales/Barrios'),
        autorizaciones: () => import('@/components/misional/atencionUsuario/autorizaciones/Autorizaciones'),
        registroSolicitudAutorizacion: () => import('@/components/misional/atencionUsuario/autorizaciones/RegistroSolicitudAutorizacion'),
        registroAutorizacion: () => import('@/components/misional/atencionUsuario/autorizaciones/RegistroAutorizacion'),
        detalleAutorizacion: () => import('@/components/misional/atencionUsuario/autorizaciones/DetalleAutorizacion'),
        solicitudesAutorizacion: () => import('@/components/misional/atencionUsuario/solicitudesAutorizacion/SolicitudesAutorizacion'),
        detalleSolicitudAutorizacion: () => import('@/components/misional/atencionUsuario/solicitudesAutorizacion/DetalleSolicitudAutorizacion'),
        estudioSolicitudAutorizacion: () => import('@/components/misional/atencionUsuario/solicitudesAutorizacion/EstudioSolicitudAutorizacion'),
        // CONTRATACIÓN ESTATAL
        contratistas: () => import('@/components/administrativo/contratacionEstatal/contratistas/Contratistas'),
        registroContratista: () => import('@/components/administrativo/contratacionEstatal/contratistas/RegistroContratista'),
        bienesYServicios: () => import('@/components/administrativo/contratacionEstatal/bienesYServicios/BienesYServicios'),
        planAdquisiciones: () => import('@/components/administrativo/contratacionEstatal/planAdquisiciones/PlanAdquisiciones'),
        registroPlanAdquisiciones: () => import('@/components/administrativo/contratacionEstatal/planAdquisiciones/RegistroPlanAdquisiciones'),
        aseguradoras: () => import('@/components/administrativo/contratacionEstatal/aseguradoras/Aseguradoras'),
        registroAseguradoras: () => import('@/components/administrativo/contratacionEstatal/aseguradoras/RegistroAseguradora'),
        tipoPoliza: () => import('@/components/administrativo/contratacionEstatal/TipoPoliza/TipoPoliza'),
        registroTipoPoliza: () => import('@/components/administrativo/contratacionEstatal/TipoPoliza/RegistroTipoPoliza'),
        abogados: () => import('@/components/administrativo/contratacionEstatal/Abogados/Abogados'),
        registroAbogado: () => import('@/components/administrativo/contratacionEstatal/Abogados/RegistroAbogado'),
        interventores: () => import('@/components/administrativo/contratacionEstatal/Interventores/Interventores'),
        registroInterventor: () => import('@/components/administrativo/contratacionEstatal/Interventores/RegistroInterventores'),
        supervisores: () => import('@/components/administrativo/contratacionEstatal/Supervisores/Supervisores'),
        registroSupervisores: () => import('@/components/administrativo/contratacionEstatal/Supervisores/RegistroSupervisor'),
        // Procesos contractuales
        procesosContractuales: () => import('@/components/administrativo/contratacionEstatal/procesosContractuales/procesosContractuales/ProcesosContractuales'),
        registroProcesoContractual: () => import('@/components/administrativo/contratacionEstatal/procesosContractuales/procesosContractuales/RegistroProcesoContractual'),
        // Contratos
        contratos: () => import('@/components/administrativo/contratacionEstatal/procesosContractuales/contratos/Contratos'),
        registroContrato: () => import('@/components/administrativo/contratacionEstatal/procesosContractuales/contratos/RegistroContrato'),
        minutaContrato: () => import('@/components/administrativo/contratacionEstatal/procesosContractuales/contratos/MinutaContrato'),
        // // Atención al usuario
        cums: () => import('@/components/misional/atencionUsuario/cums/Cums'),
        registroCums: () => import('@/components/misional/atencionUsuario/cums/RegistroCums'),
        cups: () => import('@/components/misional/atencionUsuario/cups/Cups'),
        recepcionPqrs: () => import('@/components/misional/atencionUsuario/pqrs/RecepcionPqrs'),
        registroRecepcionPqrs: () => import('@/components/misional/atencionUsuario/pqrs/RegistroRecepcionPqrs'),
        funcionarioPqrs: () => import('@/components/misional/atencionUsuario/pqrs/FuncionarioPqrs'),
        detallePqrs: () => import('@/components/misional/atencionUsuario/pqrs/DetallePqrs'),
        estadisticasPqrs: () => import('@/components/misional/atencionUsuario/pqrs/EstadisticasPqrs'),
        registroCups: () => import('@/components/misional/atencionUsuario/cups/RegistroCups'),
        aportes: () => import('@/components/misional/aseguramiento/relacionesLaborales/aportes/Aportes'),
        compensaciones: () => import('@/components/misional/aseguramiento/relacionesLaborales/compensaciones/Compensaciones'),
        relacionesLaborales: () => import('@/components/misional/aseguramiento/relacionesLaborales/RelacionesLaborales'),
        detalleRelacionLaboral: () => import('@/components/misional/aseguramiento/relacionesLaborales/DetalleRelacionLaboral'),
        primeraInstancia: () => import('@/components/misional/atencionUsuario/liquidacionIncapacidades/PrimeraInstancia'),
        registroPrimeraInstancia: () => import('@/components/misional/atencionUsuario/liquidacionIncapacidades/RegistroPrimeraInstancia'),
        detallePrimeraInstancia: () => import('@/components/misional/atencionUsuario/liquidacionIncapacidades/DetallePrimeraInstancia'),
        segundaInstancia: () => import('@/components/misional/atencionUsuario/liquidacionIncapacidades/SegundaInstancia'),
        detalleIncapacidades: () => import('@/components/misional/atencionUsuario/liquidacionIncapacidades/DetalleIncapacidades'),
        // // Oficina juridica
        juzgados: () => import('@/components/administrativo/oficinaJuridica/juzgados/Juzgados'),
        tutelas: () => import('@/components/administrativo/oficinaJuridica/tutelas/Tutelas'),
        registroTutelas: () => import('@/components/administrativo/oficinaJuridica/tutelas/RegistroTutelas'),
        detalleTutela: () => import('@/components/administrativo/oficinaJuridica/tutelas/DetalleTutela'),
        contestacionesDetalle: () => import('@/components/administrativo/oficinaJuridica/tutelas/detalles/ContestacionesDetalle'),
        fallosDetalle: () => import('@/components/administrativo/oficinaJuridica/tutelas/detalles/FallosDetalle'),
        impugnacionesDetalle: () => import('@/components/administrativo/oficinaJuridica/tutelas/detalles/ImpugnacionesDetalle'),
        desacatosDetalle: () => import('@/components/administrativo/oficinaJuridica/tutelas/detalles/DesacatosDetalle'),
        bitacorasDetalle: () => import('@/components/administrativo/oficinaJuridica/tutelas/detalles/BitacorasDetalle'),
        // // inventarios
        configuracionInventarios: () => import('@/components/administrativo/inventarios/ConfiguracionInventarios/ConfiguracionInventarios'),
        gruposinventarios: () => import('@/components/administrativo/inventarios/Grupos/Grupos'),
        registroGruposInventarios: () => import('@/components/administrativo/inventarios/Grupos/RegistroGrupos'),
        subgruposinventarios: () => import('@/components/administrativo/inventarios/Subgrupos/Subgrupos'),
        registroSubgruposInventarios: () => import('@/components/administrativo/inventarios/Subgrupos/RegistroSubgrupos'),
        almaceninventarios: () => import('@/components/administrativo/inventarios/Almacen/Almacen'),
        registroAlmacenInvetarios: () => import('@/components/administrativo/inventarios/Almacen/RegistroAlmacen'),
        unidadmedidainventarios: () => import('@/components/administrativo/inventarios/UnidadMedida/UnidadMedida'),
        registroUnidadMedidaInventarios: () => import('@/components/administrativo/inventarios/UnidadMedida/RegistroUnidadMedida'),
        productos: () => import('@/components/administrativo/inventarios/Productos/Productos'),
        registroProducto: () => import('@/components/administrativo/inventarios/Productos/RegistroProducto'),
        // // Talento humano
        gruposempleados: () => import('@/components/administrativo/TalentoHumano/GruposEmpleados/GruposEmpleados'),
        registroGruposEmpleados: () => import('@/components/administrativo/TalentoHumano/GruposEmpleados/RegistroGruposEmpleados'),
        subgruposempleados: () => import('@/components/administrativo/TalentoHumano/SubgruposEmpleados/SubgruposEmpleados'),
        registroSubgruposEmpleados: () => import('@/components/administrativo/TalentoHumano/SubgruposEmpleados/RegistroSubgruposEmpleados'),
        fondostalentohumano: () => import('@/components/administrativo/TalentoHumano/Fondos/Fondos'),
        registroFondosTalentoHumano: () => import('@/components/administrativo/TalentoHumano/Fondos/RegistroFondos'),
        nivelescargotalentohumano: () => import('@/components/administrativo/TalentoHumano/NivelesCargo/NivelesCargo'),
        registroNivelesCargoTalentoHumano: () => import('@/components/administrativo/TalentoHumano/NivelesCargo/RegistroNivelesCargo'),
        cargosempleadostalentohumano: () => import('@/components/administrativo/TalentoHumano/CargosEmpleados/CargosEmpleados'),
        registroCargosEmpleadosTalentoHumano: () => import('@/components/administrativo/TalentoHumano/CargosEmpleados/RegistroCargosEmpleados'),
        gradoprofesionalismo: () => import('@/components/administrativo/TalentoHumano/GradoProfesionalismo/GradoProfesionalismo'),
        registroGradoProfesionalismo: () => import('@/components/administrativo/TalentoHumano/GradoProfesionalismo/RegistroGradoProfesionalismo'),
        motivosretirotalentohumano: () => import('@/components/administrativo/TalentoHumano/MotivosRetiro/MotivosRetiro'),
        registroMotivosRetiroTalentoHumano: () => import('@/components/administrativo/TalentoHumano/MotivosRetiro/RegistroMotivoRetiro'),
        empleado: () => import('@/components/administrativo/TalentoHumano/Empleado/Empleado'),
        registroEmpleado: () => import('@/components/administrativo/TalentoHumano/Empleado/RegistroEmpleado'),
        encargos: () => import('@/components/administrativo/TalentoHumano/encargos/Encargos'),
        // // Presupuesto
        entidadresolucion: () => import('@/components/administrativo/presupuesto/EntidadResolucion/EntidadResolucion'),
        registroEntidadResolucion: () => import('@/components/administrativo/presupuesto/EntidadResolucion/RegistroEntidadResolucion'),
        dependencia: () => import('@/components/administrativo/presupuesto/Dependencia/Dependencia'),
        registroDependencia: () => import('@/components/administrativo/presupuesto/Dependencia/RegistroDependencia'),
        tipoingreso: () => import('@/components/administrativo/presupuesto/TipoIngreso/TipoIngreso'),
        registroTipoIngreso: () => import('@/components/administrativo/presupuesto/TipoIngreso/RegistroTipoIngreso'),
        tipogasto: () => import('@/components/administrativo/presupuesto/TipoGasto/TipoGasto'),
        registroTipoGasto: () => import('@/components/administrativo/presupuesto/TipoGasto/RegistroTipoGasto'),
        tiporecurso: () => import('@/components/administrativo/presupuesto/TipoRecurso/TipoRecurso'),
        registroTipoRecurso: () => import('@/components/administrativo/presupuesto/TipoRecurso/RegistroTipoRecurso'),
        conceptopresupuesto: () => import('@/components/administrativo/presupuesto/ConceptoPresupuesto/ConceptoPresupuesto'),
        registroConceptoPresupuesto: () => import('@/components/administrativo/presupuesto/ConceptoPresupuesto/RegistroConceptoPresupuesto'),
        periodos4505: () => import('@/components/misional/validador4505/Periodos/Periodos'),
        registroPeriodos4505: () => import('@/components/misional/validador4505/Periodos/RegistroPeriodo4505'),
        validador: () => import('@/components/misional/validador4505/Validador4505'),
        reglasValidador4505: () => import('@/components/misional/validador4505/ConfigurarReglasValidacion4505'),
        unificador4505: () => import('@/components/misional/validador4505/Unificador4505'),
        estadisticas4505: () => import('@/components/misional/validador4505/Estadisticas4505'),
        estructuraPresupuestal: () => import('@/components/administrativo/presupuesto/EstructuraPresupuestal/EstructuraPresupuestal'),
        presupuestoInicialDeIngresos: () => import('@/components/administrativo/presupuesto/presupuestoInicialDeIngresos/PresupuestoInicialDeIngresos'),
        tablaPresupuestoInicialDeIngresos: () => import('@/components/administrativo/presupuesto/presupuestoInicialDeIngresos/TablaPresupuestoInicialDeIngresos'),
        presupuestoInicialDeGastos: () => import('@/components/administrativo/presupuesto/presupuestoInicialDeGastos/PresupuestoInicialDeGastos'),
        tablaPresupuestoInicialDeGastos: () => import('@/components/administrativo/presupuesto/presupuestoInicialDeGastos/TablaPresupuestoInicialDeGastos'),
        modificacionPresupuestal: () => import('@/components/administrativo/presupuesto/modificacionPresupuestal/ModificacionPresupuestal'),
        registroModificacionPresupuestal: () => import('@/components/administrativo/presupuesto/modificacionPresupuestal/RegistroModificacion'),
        trasladoPresupuestal: () => import('@/components/administrativo/presupuesto/trasladoPresupuestal/TrasladoPresupuestal'),
        registroTrasladoPresupuestal: () => import('@/components/administrativo/presupuesto/trasladoPresupuestal/RegistroTraslado'),
        CDP: () => import('@/components/administrativo/presupuesto/cdp/CDP'),
        registroCDP: () => import('@/components/administrativo/presupuesto/cdp/RegistroCDP'),
        rp: () => import('@/components/administrativo/presupuesto/rp/Rp'),
        registroRp: () => import('@/components/administrativo/presupuesto/rp/RegistroRp'),
        obligaciones: () => import('@/components/administrativo/presupuesto/obligaciones/Obligaciones'),
        registroObligaciones: () => import('@/components/administrativo/presupuesto/obligaciones/RegistroObligaciones'),
        ordenesDePago: () => import('@/components/administrativo/presupuesto/ordenesDePago/OrdenesDePago'),
        registroOrdenesDePago: () => import('@/components/administrativo/presupuesto/ordenesDePago/RegistroOrdenesDePago'),
        // RED DE SERVICIOS
        // Asignación Masiva
        gruposIPS: () => import('@/components/misional/redservicios/gruposIPS/GruposIPS'),
        asignacionmasiva: () => import('@/components/misional/redservicios/asignacionMasiva/AsignacionesMasivas'),
        registroAsignacionMasiva: () => import('@/components/misional/redservicios/asignacionMasiva/registroAsignacionMasiva/RegistroAsignacionMasiva'),
        detalleAsignacionMasiva: () => import('@/components/misional/redservicios/asignacionMasiva/registroAsignacionMasiva/DetalleAsignacionMasiva'),
        // Entidades
        entidades: () => import('@/components/misional/redservicios/entidades/Entidades'),
        registroEntidad: () => import('@/components/misional/redservicios/entidades/registroEntidad/RegistroEntidad'),
        // Planes de Cobertura
        planesCobertura: () => import('@/components/misional/redservicios/planesCobertura/PlanesCobertura'),
        registroPlanCobertura: () => import('@/components/misional/redservicios/planesCobertura/RegistroPlanCobertura'),
        // RIIPS
        reglas: () => import('@/components/misional/rips/ConfigurarReglasValidacion'),
        entidadesTemporales: () => import('@/components/misional/rips/HabilitarEntidad'),
        rips: () => import('@/components/misional/rips/RipsValidados'),
        cie10s: () => import('@/components/misional/rips/Cie10'),
        // Atención Usuario - Centro Regulador
        referencias: () => import('@/components/misional/atencionUsuario/centro_regulador/Referencia'),
        registroReferencia: () => import('@/components/misional/atencionUsuario/centro_regulador/RegistroReferencia'),
        detallesReferencia: () => import('@/components/misional/atencionUsuario/centro_regulador/DetallesReferencia'),
        encuestas: () => import('@/components/misional/atencionUsuario/encuesta_salud/Encuesta'),
        registroEncuesta: () => import('@/components/misional/atencionUsuario/encuesta_salud/RegistroEncuesta'),
        // Auditoria Y Cuentas
        auditores: () => import('@/components/administrativo/auditoriaCuentas/auditores/Auditores'),
        registroAuditores: () => import('@/components/administrativo/auditoriaCuentas/auditores/RegistroAuditores'),
        concurrencias: () => import('@/components/administrativo/auditoriaCuentas/concurrencias/Concurrencias'),
        registroConcurrencias: () => import('@/components/administrativo/auditoriaCuentas/concurrencias/RegistroConcurrencias'),
        detalleConcurrencia: () => import('@/components/administrativo/auditoriaCuentas/concurrencias/DetalleConcurrencia'),
        radicadosAsignados: () => import('@/components/administrativo/auditoriaCuentas/radicadosAsignados/RadicadoAsignado'),
        facturasradicadas: () => import('@/components/administrativo/auditoriaCuentas/radicadosAsignados/DetalleFacturasRadicadas'),
        detalleFacturaRadicada: () => import('@/components/administrativo/auditoriaCuentas/radicadosAsignados/detalleFactura/DetalleFactura'),
        concurrenciasAsignadas: () => import('@/components/administrativo/auditoriaCuentas/concurrencias/ConcurrenciasAsignadas'),
        // Reportes
        reportes: () => import('@/components/reportes/Reportes'),
        configuracionReportes: () => import('@/components/reportes/ConfiguracionesReportes'),
        registroReporte: () => import('@/components/reportes/RegistroReporte'),
        // Radicacion de Cuentas
        cmradicadas: () => import('@/components/misional/radicacionCuentas/CmRadicada'),
        registroRadicada: () => import('@/components/misional/radicacionCuentas/RegistroCuentaradicar'),
        censos: () => import('@/components/administrativo/auditoriaCuentas/censos/VCenso'),
        auPacientes: () => import('@/components/administrativo/auditoriaCuentas/censos/AuditoriaPacientes'),
        // MIPRES prescripciones
        prescripciones: () => import('@/components/mipres/prescripciones/Prescripciones'),
        detallePrescripcion: () => import('@/components/mipres/prescripciones/DetallePrescripcion'),
        // MIPRES direccionamientos
        direccionamientos: () => import('@/components/mipres/direccionamientos/Direccionamientos'),
        // MIPRES tutelas
        tutelasMipres: () => import('@/components/mipres/tutelas/Tutelas'),
        detalleTutelaMipres: () => import('@/components/mipres/tutelas/DetalleTutela'),
        auditoriaMS: () => import('@/components/misional/aseguramiento/auditorias/AuditoriaMS'),
        // MIPRES Reportes de entrega
        reportesentrega: () => import('@/components/mipres/reportesEntrega/ReportesEntrega'),
        // INTELIGENCIA DE NEGOCIOS
        inteligencianegocioprincipal: () => import('@/components/inteligenciaNegocios/Principal'),
        // agregado RJPT Vigencia Traslado y periodo de liquidación
        vigenciaTraslado: () => import('@/components/administrativo/generales/VigenciaTraslado'),
        periodoLiquidacion: () => import('@/components/administrativo/generales/PeriodosLiquidacion'),
        // RJPT TALENTO HUMANO clase de fondo
        claseFondo: () => import('@/components/administrativo/TalentoHumano/Fondos/ClaseFondos'),
        // RJPT TALENTO HUMANO clase de fondo
        fondo: () => import('@/components/administrativo/TalentoHumano/Fondos/FondosC'),
        // RJPT TALENTO HUMANO salario minimo
        salariominimo: () => import('@/components/administrativo/TalentoHumano/SalarioMinimo'),
        // RJPT TALENTO HUMANO extra laboral
        extraLaboral: () => import('@/components/administrativo/TalentoHumano/ExtraLaboral'),
        entidadFinanciera: () => import('@/components/administrativo/TalentoHumano/Fondos/EntidadesFinancieras'),
        configuracionsalario: () => import('@/components/administrativo/TalentoHumano/ConfSalarioMinimo'),
        profesion: () => import('@/components/administrativo/TalentoHumano/TBProfesion'),
        scempleados: () => import('@/components/administrativo/TalentoHumano/Empleado/SCEmpleado'),
        registroscEmpleado: () => import('@/components/administrativo/TalentoHumano/Empleado/RegistroSCEmpleado'),
        configbasicTHumano: () => import('@/components/administrativo/TalentoHumano/ConfiguracionesBasicas'),
        detalleContratosEmpleado: () => import('@/components/administrativo/TalentoHumano/Empleado/ConfiguracionContratoEmpleado/DetalleContratosEmpleado'),
        detalleExtralabora: () => import('@/components/administrativo/TalentoHumano/Empleado/ConfiguracionContratoEmpleado/DetalleExtraslaborales'),
        preScnomina: () => import('@/components/administrativo/TalentoHumano/ScLiquidacionNomina'),
        registroNominal: () => import('@/components/administrativo/TalentoHumano/RegistroNominalLiquidacion'),
        incapacidad: () => import('@/components/administrativo/TalentoHumano/Empleado/Incapacidad'),
        recCompensaciones: () => import('@/components/misional/aseguramiento/relacionesLaborales/recompensaciones/Recompensaciones'),
        recLogBancario: () => import('@/components/misional/aseguramiento/relacionesLaborales/recompensaciones/Relogbancario'),
        registroIncapacidad: () => import('@/components/administrativo/TalentoHumano/Empleado/GestionIncapacidad'),
        tiposoporte: () => import('@/components/misional/atencionUsuario/tiposSoporte/TipoSoporte'),
        tiposoportexincapacidad: () => import('@/components/misional/atencionUsuario/tiposSoporte/TipoSoporteIncapacidad'),
        registroSoporteIncapacidad: () => import('@/components/misional/atencionUsuario/tiposSoporte/RegistroSoporteIncapacidad'),
        preferencia: () => import('@/components/misional/atencionUsuario/TBPreferencia'),
        auditoriaprestaciones: () => import('@/components/misional/atencionUsuario/auditorias_prestaciones_economicas/AuditoriaPrestacionEconomica'),
        registroAuditoriaPresEcon: () => import('@/components/misional/atencionUsuario/auditorias_prestaciones_economicas/GestionAuditoriaPrestacionEconomica'),
        diasFestivos: () => import('@/components/misional/atencionUsuario/TBDiaFestivo'),
        rechazo: () => import('@/components/misional/atencionUsuario/TBRechazoPS'),
        modificarSoportesAuditoria: () => import('@/components/misional/atencionUsuario/auditorias_prestaciones_economicas/EdicionSoportesAuditoria'),
        envioPrestacion: () => import('@/components/misional/atencionUsuario/envio_prestaciones/EnvioPrestaciones'),
        facturaGeneral: () => import('@/components/administrativo/auditoriaCuentas/facturas/TBFacturaGeneral'),
        facturaRIPS: () => import('@/components/administrativo/auditoriaCuentas/facturas/TBFacturaRips')
      },
      beforeEnter: autenticado
    },
    {
      path: '/404',
      name: 'Error404',
      component: () => import('@/components/general/error404')
    },
    {
      path: '*',
      redirect: '/404'
    }
  ]
})
