<?php

namespace App\Models\Presupuesto;

use App\User;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Jedrzej\Pimpable\PimpableTrait;
use Jedrzej\Searchable\Constraint;
use OwenIt\Auditing\Contracts\Auditable;

class PrModPresupuestale extends Model implements Auditable
{
    use \OwenIt\Auditing\Auditable;
    use PimpableTrait;
    protected $table = 'pr_mod_presupuestales';

    protected $fillable = [
        'concepto_anulacion',
        'periodo',
        'consecutivo_presupuestal',
        'detalle_modificacion',
        'documento',
        'estado',
        'fecha',
        'fecha_anulacion',
        'gs_strgasto_id',
        'pr_stringreso_id',
        'gs_usuario_id',
        'tipo'
    ];

    protected $searchable = ['tipo','estado','search'];

    public function detalles ()
    {
        return $this->hasMany(PrModDetPresupuestale::class, 'pr_mod_presupuestal_id');
    }

    public function presupuesto_inicial_gasto () {
        return $this->belongsTo(PrStrgasto::class, 'gs_strgasto_id');
    }

    public function presupuesto_inicial_ingreso () {
        return $this->belongsTo(PrStringreso::class, 'pr_stringreso_id');
    }

    public function usuario ()
    {
        return $this->belongsTo(User::class, 'gs_usuario_id');
    }

    protected function processSearchFilter(Builder $builder, Constraint $constraint)
    {
        // this logic should happen for LIKE/EQUAL operators only

        if ($constraint->getOperator() === Constraint::OPERATOR_LIKE || $constraint->getOperator() === Constraint::OPERATOR_EQUAL) {
            $builder->where(function ($query) use ($constraint) {
                $query->where('documento', $constraint->getOperator(), $constraint->getValue())
                    ->orWhere('consecutivo_presupuestal', $constraint->getOperator(), $constraint->getValue());
            });
//                ->orWhere('tipo', $constraint->getOperator(), $constraint->getValue());
            return true;
        }
        // default logic should be executed otherwise
        return false;
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        PrModPresupuestale::creating(function ($table){
            if(Auth::user()){
                $table->gs_usuario_id = Auth::user()->id;
                if ($table->tipo === 'Ingreso') {
                    $table->consecutivo_presupuestal  = PrModPresupuestale::where('tipo','=','Ingreso')->max('consecutivo_presupuestal') + 1;
                } elseif ($table->tipo === 'Gasto') {
                    $table->consecutivo_presupuestal  = PrModPresupuestale::where('tipo','=','Gasto')->max('consecutivo_presupuestal') + 1;
                }
            }
//            PrModPresupuestale::max('consecutivo_presupuestal');
        });

    }
}
