<?php

namespace App\Models\Presupuesto;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class PrNiveles extends Model
{
    public $timestamps = false;
    protected $fillable = ['codigo','nombre','digitos'];
    
    protected $appends = ['removable'];

    public function getRemovableAttribute()
    {
        $siguiente_nivel = PrNiveles::where('nivel',$this->nivel + 1)->count();
        return $this->conceptos->count() || $siguiente_nivel ? false : true;
    }

    public function conceptos()
    {
        return $this->hasMany(PrConcepto::class, 'pr_nivel_id');
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        PrNiveles::creating(function ($table){
            $table->nivel = PrNiveles::max('nivel') + 1;
        });

    }
}
