<?php

namespace App\Models\ContratacionEstatal;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Jedrzej\Pimpable\PimpableTrait;
use Jedrzej\Searchable\Constraint;
use OwenIt\Auditing\Contracts\Auditable;

class CePlanadquisicione extends Model implements Auditable
{
    use \OwenIt\Auditing\Auditable;
    use PimpableTrait;

    protected $fillable = ['anio', 'descripcion', 'gs_usuario_id', 'estado'];

    public $searchable = ['anio', 'descripcion', 'estado', 'search'];

    public function detalles(){
        return $this->hasMany(CeDetplanadquisicione::class, 'ce_planadquisicione_id');
    }

    protected function processSearchFilter(Builder $builder, Constraint $constraint)
    {
        // this logic should happen for LIKE/EQUAL operators only

        if ($constraint->getOperator() === Constraint::OPERATOR_LIKE || $constraint->getOperator() === Constraint::OPERATOR_EQUAL) {
            $builder->where('anio', $constraint->getOperator(), $constraint->getValue())
                ->orWhere('descripcion', $constraint->getOperator(), $constraint->getValue())
                ->orWhere('estado', $constraint->getOperator(), $constraint->getValue());
            return true;
        }
        // default logic should be executed otherwise
        return false;
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        CePlanadquisicione::saving(function ($table){
            if(Auth::user()){
                $table->gs_usuario_id  = Auth::user()->id;
            }
        });

    }
}
