<?php

namespace App\Models\ContratacionEstatal;

use App\Models\Presupuesto\PrCdp;
use App\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Jedrzej\Pimpable\PimpableTrait;
use OwenIt\Auditing\Contracts\Auditable;

/**
 * @author Jorge Eduardo Hernández 01-06-2020
 * @copyright Creando Soluciones Informaticas LTDA
 *
 * Class CeProconminutaPrCdps
 * @package App\Models\ContratacionEstatal
 */

class CeProconminutaPrCdps extends Model implements Auditable
{
    use \OwenIt\Auditing\Auditable;
    use PimpableTrait;

    protected $fillable = ['ce_proconminuta_id','pr_cdp_id','valor_descontado','valor_cdp_anterior','gs_usuario_id'];

    public function cdp ()
    {
        return $this->belongsTo(PrCdp::class, 'pr_cdp_id');
    }

    public function usuario () {
        return $this->belongsTo(User::class,'gs_usuario_id');
    }

    public static function boot(){
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function ($table){
            if(Auth::user()){
                $table->gs_usuario_id  = Auth::user()->id;
            }
        });
    }
}
