<?php

namespace App\Models\ContratacionEstatal;

use App\Models\Pagos\PgUniapoyo;
use App\Models\Presupuesto\PrCdp;
use App\Models\Presupuesto\PrDependencia;
use App\Models\TalentoHumano\TbDependencia;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Jedrzej\Pimpable\PimpableTrait;
use OwenIt\Auditing\Contracts\Auditable;

class CeProcontractuale extends Model implements Auditable
{
    use \OwenIt\Auditing\Auditable;

    use PimpableTrait;

    protected $fillable = [
        'consecutivo',
        'estado',
        'gs_usuario_id',
        'objeto',
        'pr_dependencia_id',
        'servicios_salud'
    ];
    protected $hidden = ['created_at', 'updated_at'];

    public $sortable = ['consecutivo', 'dependencia'];

    protected $searchable = ['objeto', 'estado'];

    public function dependencia()
    {
        return $this->belongsTo(TbDependencia::class, 'pr_dependencia_id');
    }

    public function contrato()
    {
        return $this->hasOne(CeProconminuta::class, 'ce_procontractuale_id');
    }

    public function estudiosPrevios()
    {
        return $this->hasOne(CeProconestprevio::class, 'ce_procontractuale_id');
    }

    public function allRelations()
    {
        return [
            'dependencia',
            'estudiosPrevios.imputacionPresupuestal.strgasto.rubro',
            'estudiosPrevios.actividades',
            'estudiosPrevios.forpagos',
            'estudiosPrevios.garantias.garantia',
            'estudiosPrevios.supervisor',
            'estudiosPrevios.modalidad',
            'estudiosPrevios.proconminutageos',
            'estudiosPrevios.proconminutageos.municipio',
            'estudiosPrevios.proconminutageos.upcservicios',
            'estudiosPrevios.proconminutageos.upcservicios.servicio',
            'estudiosPrevios.proconminutageos.upcedades',
            'estudiosPrevios.proconminutageos.upcedades.rangoupc',
            'contrato.prcdps.cdp'
        ];
    }

    public function sortDependencia($query, $direction = 'desc')
    {
        return $query->leftJoin('pr_dependencias', 'ce_procontractuales.pr_dependencia_id', '=', 'pr_dependencias.id')
            ->orderBy('pr_dependencias.nombre', $direction);
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        CeProcontractuale::creating(function ($table) {
            if (Auth::user()) {
                $table->gs_usuario_id = Auth::user()->id;
            }
            $table->consecutivo = CeProcontractuale::max('consecutivo') + 1;
        });

    }


}
