services:
  srv-mysql:
    image: mysql:8.0.15
    container_name: srv-mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    volumes:
      - mysql_data:/var/lib/mysql
      #- ./backupdb/my.cnf:/etc/mysql/my.cnf            
      - ./backupdb:/var/tmp/scripts
      - ./backupdb/load.sql:/docker-entrypoint-initdb.d/1.sql
      #- ./backupdb/init.sql:/docker-entrypoint-initdb.d/2.sql

  srv-redis:
    image: redis:latest
    container_name: srv-redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD} # Cambia esta contraseña
    command: ["redis-server", "--requirepass", "$REDIS_PASSWORD"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  gce-backend:
    container_name: gce-backend
    build:
      context: .
      dockerfile: Dockerfile-back
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    volumes:
      - ./backend:/var/www/html
      - ./apache2/php.ini:/etc/php/7.2/apache2/php.ini
    expose:
      - "8000"
      - "6001"
    depends_on:
      - srv-mysql
      - srv-redis

  gce-frontend:
    image: php:8.1-apache # Usamos la imagen de PHP con Apache para servir el frontend
    container_name: gce-frontend
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/dist
    volumes:
      - ./frontend:/var/www/html
      - ./apache2/frontend.conf:/etc/apache2/sites-available/frontend.conf
      - ./apache2/front-ports.conf:/etc/apache2/ports.conf
    command: /bin/bash -c "a2ensite frontend.conf && a2enmod rewrite && apache2-foreground"
    expose:
      - "8080"
    depends_on:
      -  gce-backend

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:8080"
      - "8000:8000"
      - "6001:6001"
    depends_on:
      - gce-backend
      - gce-frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

# Names our volume
volumes:
  mysql_data:
  redis_data:
