# Base image
FROM ubuntu:18.04

# Environment setup for non-interactive installations
ENV DEBIAN_FRONTEND=noninteractive

# Update system and configure locales and timezone
RUN apt-get update && apt-get install -y \
    tzdata \
    software-properties-common \
    locales \
    && locale-gen en_IE.UTF-8

# Configure timezone
RUN ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime && dpkg-reconfigure --frontend noninteractive tzdata

# Install PHP 7.2 and Apache
RUN add-apt-repository ppa:ondrej/php -y && \
    apt-get update && \
    apt-get install -y \
    php7.2=7.2.24-0ubuntu0.18.04.17 \
    php7.2-cli \
    php7.2-fpm \
    php7.2-mysql \
    php7.2-xml \
    php7.2-mbstring \
    php7.2-curl \
    php7.2-zip \
    php7.2-intl \
    php7.2-gd \
    php7.2-soap \
    apache2 \
    libapache2-mod-php7.2 \
    git \
    zip \
    unzip \
    curl \
    # Install libraries required by PHP extensions
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    # Install additional required PHP extensions
    php7.2-bcmath \
    php7.2-pdo \
    php7.2-pdo-mysql \
    && apt-get clean

# Install Node.js (version 8) for Laravel Echo Server
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - && \
    apt-get install -y nodejs && \
    npm install -g pm2 && \
    npm install -g laravel-echo-server

# Install Supervisor
RUN apt-get install -y supervisor

# Apache configuration
COPY ./apache2/backend.conf /etc/apache2/sites-available/backend.conf
COPY ./apache2/back-ports.conf /etc/apache2/ports.conf
COPY ./apache2/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
RUN a2ensite backend.conf && a2enmod headers rewrite

# Set working directory
WORKDIR /var/www/html

# Expose ports for Apache and Laravel Echo Server
EXPOSE 8000 6001

# Command to start Supervisor
CMD ["/usr/bin/supervisord"]
