<?php

namespace App\Models\ContratacionEstatal;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Jedrzej\Pimpable\PimpableTrait;
use Jedrzej\Searchable\Constraint;
use OwenIt\Auditing\Contracts\Auditable;

class CeBienservicio extends Model implements Auditable
{
    use \OwenIt\Auditing\Auditable;
    use PimpableTrait;

    protected $fillable = [
        'ce_clasbienservicio_id', 'codigo', 'estado', 'gs_usuario_id', 'nombre'
    ];
    protected $hidden = [
        'created_at', 'updated_at'
    ];

    protected $searchable = ['nombre', 'codigo','search'];

    public function clasbienservicio () {
        return $this->belongsTo(CeClasbienservicio::class, 'ce_clasbienservicio_id');
    }

    protected function processSearchFilter(Builder $builder, Constraint $constraint)
    {
        // this logic should happen for LIKE/EQUAL operators only

        if ($constraint->getOperator() === Constraint::OPERATOR_LIKE || $constraint->getOperator() === Constraint::OPERATOR_EQUAL) {
            $builder->where('nombre', $constraint->getOperator(), $constraint->getValue())
                ->orWhere('codigo', $constraint->getOperator(), $constraint->getValue());
            return true;
        }
        // default logic should be executed otherwise
        return false;
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        CeBienservicio::saving(function ($table){
            if(Auth::user()){
                $table->gs_usuario_id  = Auth::user()->id;
            }
        });

    }
}
