<?php

namespace App\Models\CuentasMedicas;

use App\Models\General\GnArchivo;
use App\Models\RedServicios\RsEntidade;
use App\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Jedrzej\Pimpable\PimpableTrait;
use OwenIt\Auditing\Contracts\Auditable;

class CmCenso extends Model implements Auditable
{
    use \OwenIt\Auditing\Auditable;
    use PimpableTrait;

    protected $table = 'cm_censos';
    protected $fillable = [
        'fecha',
        'ips_id',
        'registros',
        'archivo_id',
        'user_id',
        'informe_carga'
    ];

    protected $searchable = [];
    protected $sortable = ['ips:nombre'];
    protected $appends = ['cantidad_pacientes'];

    public function archivo () {
        return $this->belongsTo(GnArchivo::class, 'archivo_id');
    }

    public function usuario()
    {
        return $this->belongsTo(User::class,'user_id');
    }

    public function ips () {
        return $this->belongsTo(RsEntidade::class,'ips_id');
    }

    public function pacientes()
    {
        return $this->hasMany(CmPacientesHospitalario::class,'cm_censo_id');
    }

    public function getCantidadPacientesAttribute($key)
    {
        return $this->pacientes()->count();
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        CmCenso::creating(function ($table){
            if(Auth::user()){
                $table->user_id  = Auth::user()->id;
            }
        });

    }

}
