<?php

namespace App\Models\CuentasMedicas;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Jedrzej\Pimpable\PimpableTrait;
use Jedrzej\Searchable\Constraint;
use OwenIt\Auditing\Contracts\Auditable;

class CmEventoadversoips extends Model implements Auditable
{
    use PimpableTrait;
    use \OwenIt\Auditing\Auditable;

    protected $table = 'cm_eventoadversoipss';
    protected $searchable = ['search'];
    protected $fillable = ['codigo','nombre'];

    protected function processSearchFilter(Builder $builder, Constraint $constraint)
    {
        // this logic should happen for LIKE/EQUAL operators only
        if ($constraint->getOperator() === Constraint::OPERATOR_LIKE || $constraint->getOperator() === Constraint::OPERATOR_EQUAL) {
            $builder->where(function ($query) use($builder,$constraint){
                $query->where('codigo', $constraint->getOperator(), $constraint->getValue())
                    ->orWhere('nombre', $constraint->getOperator(), $constraint->getValue());
            });
            return true;
        }
        // default logic should be executed otherwise
        return false;
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        CmEventoadversoips::creating(function ($table) {
            $codigo_numero = CmEventoadversoips::max('id') + 1;
            $table->codigo = 'I-'.$codigo_numero;
        });
    }
}
