<?php

namespace App\Models\CuentasMedicas;

use App\User;
use Illuminate\Database\Eloquent\Model;
use Jedrzej\Pimpable\PimpableTrait;
use OwenIt\Auditing\Contracts\Auditable;

class CmRadcambio extends Model implements Auditable
{
    use PimpableTrait;
    use \OwenIt\Auditing\Auditable;

    protected $table = 'cm_radcambios';

    protected $fillable = [
        'cm_radicado_id',
        'descripcion',
        'cm_estadosrad_id',
        'aceptado',
        'gs_usuario_id',
    ];

    protected $appends = ['estado','dias'];

    public function status_check () {
        return $this->belongsTo(CmEstadosrad::class,'cm_estadosrad_id');
    }

    public function usuario () {
        return $this->belongsTo(User::class,'gs_usuario_id');
    }

    public function getEstadoAttribute($key)
    {
        return $this->status_check['estado'];
    }

    public function getDiasAttribute($key)
    {
        return $this->status_check['dias'];
    }

    //public static function boot()
    //{
    //    parent::boot(); // TODO: Change the autogenerated stub
    //
    //    CmRadcambio::creating(function ($table) {
    //        if (Auth::user()) {
    //            $table->gs_usuario_id = Auth::user()->id;
    //        }
    //    });
    //
    //}
}
