<?php

namespace App\Models\Autorizaciones;

use App\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Jedrzej\Pimpable\PimpableTrait;
use OwenIt\Auditing\Contracts\Auditable;

class AuAnexot3neg extends Model implements Auditable
{
    use \OwenIt\Auditing\Auditable;
    use PimpableTrait;

    protected $table = 'au_anexot3negs';

    protected $fillable = ['codigo', 'observacion', 'gs_usuario_id', 'au_anexot31_id'];

    public function motivo_neg()
    {
        return $this->belongsTo(Refmotivoneg::class,'codigo');
    }

    public function usuario_neg () {
        return $this->belongsTo(User::class,'gs_usuario_id');
    }

//    public function servicio () {
//        return $this->belongsTo(AuAnexot31::class,'au_anexot31_id');
//    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function ($table){
            $table->gs_usuario_id = Auth::user()->id;
        });

    }

}
