<?php

namespace App\Http\Controllers\Validador4505;

use App\Http\Controllers\Controller;
use App\Models\Validador4505\ReglasValidacion4505;
use App\Models\Validador4505\RsReglasValidacion4505;
use Illuminate\Http\Request;

class ReglasValidacionController extends Controller {

	public function index() {
		try {
			$reglasReglasValidacion = new ReglasValidacion4505(RsReglasValidacion4505::first());
			return response()->json([
				'reglas' => $reglasReglasValidacion->getReglasArray(),
				'ayudas' => $reglasReglasValidacion->descripcionReglasValidacion(),
			]);
		} catch (\Exception $e) {
			return response()->json([
				"message" => "Error en el servidor",
				"error" => $e->getMessage(),
				"trace" => $e->getTrace(),
			]);
		}
	}

	public function store(Request $request) {
		try {
			$reglasValidacion = RsReglasValidacion4505::first();
			if (is_null($request->existePrestadorServicioSaludInicioSesion) || $request->existePrestadorServicioSaludInicioSesion == false) {$reglasValidacion->existePrestadorServicioSaludInicioSesion = 0;} else { $reglasValidacion->existePrestadorServicioSaludInicioSesion = 1;}
			if (is_null($request->longitudIdentificacionAfiliado) || $request->longitudIdentificacionAfiliado == false) {$reglasValidacion->longitudIdentificacionAfiliado = 0;} else { $reglasValidacion->longitudIdentificacionAfiliado = 1;}
			if (is_null($request->primerApellidoAfiliado) || $request->primerApellidoAfiliado == false) {$reglasValidacion->primerApellidoAfiliado = 0;} else { $reglasValidacion->primerApellidoAfiliado = 1;}
			if (is_null($request->segundoApellidoAfiliado) || $request->segundoApellidoAfiliado == false) {$reglasValidacion->segundoApellidoAfiliado = 0;} else { $reglasValidacion->segundoApellidoAfiliado = 1;}
			if (is_null($request->primerNombreAfiliado) || $request->primerNombreAfiliado == false) {$reglasValidacion->primerNombreAfiliado = 0;} else { $reglasValidacion->primerNombreAfiliado = 1;}
			if (is_null($request->segundoNombreAfiliado) || $request->segundoNombreAfiliado == false) {$reglasValidacion->segundoNombreAfiliado = 0;} else { $reglasValidacion->segundoNombreAfiliado = 1;}
			if (is_null($request->fechaNacimientoAfiliado) || $request->fechaNacimientoAfiliado == false) {$reglasValidacion->fechaNacimientoAfiliado = 0;} else { $reglasValidacion->fechaNacimientoAfiliado = 1;}
			if (is_null($request->generoAfiliado) || $request->generoAfiliado == false) {$reglasValidacion->generoAfiliado = 0;} else { $reglasValidacion->generoAfiliado = 1;}
			if (is_null($request->pertenenciaEtnica) || $request->pertenenciaEtnica == false) {$reglasValidacion->pertenenciaEtnica = 0;} else { $reglasValidacion->pertenenciaEtnica = 1;}
			if (is_null($request->ocupacion) || $request->ocupacion == false) {$reglasValidacion->ocupacion = 0;} else { $reglasValidacion->ocupacion = 1;}
			if (is_null($request->nivelEducativo) || $request->nivelEducativo == false) {$reglasValidacion->nivelEducativo = 0;} else { $reglasValidacion->nivelEducativo = 1;}
			if (is_null($request->edadGestacion) || $request->edadGestacion == false) {$reglasValidacion->edadGestacion = 0;} else { $reglasValidacion->edadGestacion = 1;}
			if (is_null($request->gestacionGenero) || $request->gestacionGenero == false) {$reglasValidacion->gestacionGenero = 0;} else { $reglasValidacion->gestacionGenero = 1;}
			if (is_null($request->sifilisGestacionalCongenitaEdad) || $request->sifilisGestacionalCongenitaEdad == false) {$reglasValidacion->sifilisGestacionalCongenitaEdad = 0;} else { $reglasValidacion->sifilisGestacionalCongenitaEdad = 1;}
			if (is_null($request->sifilisGestacionalCongenitaEdadGeneroGestacion) || $request->sifilisGestacionalCongenitaEdadGeneroGestacion == false) {$reglasValidacion->sifilisGestacionalCongenitaEdadGeneroGestacion = 0;} else { $reglasValidacion->sifilisGestacionalCongenitaEdadGeneroGestacion = 1;}
			if (is_null($request->sifilisGestacionalCongenitaGenero) || $request->sifilisGestacionalCongenitaGenero == false) {$reglasValidacion->sifilisGestacionalCongenitaGenero = 0;} else { $reglasValidacion->sifilisGestacionalCongenitaGenero = 1;}
			if (is_null($request->sifilisGestacionalCongenitaGestacion) || $request->sifilisGestacionalCongenitaGestacion == false) {$reglasValidacion->sifilisGestacionalCongenitaGestacion = 0;} else { $reglasValidacion->sifilisGestacionalCongenitaGestacion = 1;}
			if (is_null($request->sifilisGestacionalCongenitaInfeccionTransmisionSexual) || $request->sifilisGestacionalCongenitaInfeccionTransmisionSexual == false) {$reglasValidacion->sifilisGestacionalCongenitaInfeccionTransmisionSexual = 0;} else { $reglasValidacion->sifilisGestacionalCongenitaInfeccionTransmisionSexual = 1;}
			if (is_null($request->hipertensionInducidaGestacionEdadSi) || $request->hipertensionInducidaGestacionEdadSi == false) {$reglasValidacion->hipertensionInducidaGestacionEdadSi = 0;} else { $reglasValidacion->hipertensionInducidaGestacionEdadSi = 1;}
			if (is_null($request->hipertensionInducidaGestacionGenero) || $request->hipertensionInducidaGestacionGenero == false) {$reglasValidacion->hipertensionInducidaGestacionGenero = 0;} else { $reglasValidacion->hipertensionInducidaGestacionGenero = 1;}
			if (is_null($request->hipertensionInducidaGestacionGestacion) || $request->hipertensionInducidaGestacionGestacion == false) {$reglasValidacion->hipertensionInducidaGestacionGestacion = 0;} else { $reglasValidacion->hipertensionInducidaGestacionGestacion = 1;}
			if (is_null($request->hipotiroidismoCongenitoEdadSi) || $request->hipotiroidismoCongenitoEdadSi == false) {$reglasValidacion->hipotiroidismoCongenitoEdadSi = 0;} else { $reglasValidacion->hipotiroidismoCongenitoEdadSi = 1;}
			if (is_null($request->hipotiroidismoCongenitoResultadoTSH) || $request->hipotiroidismoCongenitoResultadoTSH == false) {$reglasValidacion->hipotiroidismoCongenitoResultadoTSH = 0;} else { $reglasValidacion->hipotiroidismoCongenitoResultadoTSH = 1;}
			if (is_null($request->hipotiroidismoCongenitoTratamiento) || $request->hipotiroidismoCongenitoTratamiento == false) {$reglasValidacion->hipotiroidismoCongenitoTratamiento = 0;} else { $reglasValidacion->hipotiroidismoCongenitoTratamiento = 1;}
			if (is_null($request->sintomaticoRespiratorioBaciloscopiaDiagnostico) || $request->sintomaticoRespiratorioBaciloscopiaDiagnostico == false) {$reglasValidacion->sintomaticoRespiratorioBaciloscopiaDiagnostico = 0;} else { $reglasValidacion->sintomaticoRespiratorioBaciloscopiaDiagnostico = 1;}
			if (is_null($request->lepraTratamientoLepra) || $request->lepraTratamientoLepra == false) {$reglasValidacion->lepraTratamientoLepra = 0;} else { $reglasValidacion->lepraTratamientoLepra = 1;}
			if (is_null($request->obsidadDesnutricionProteicoEdadSi) || $request->obsidadDesnutricionProteicoEdadSi == false) {$reglasValidacion->obsidadDesnutricionProteicoEdadSi = 0;} else { $reglasValidacion->obsidadDesnutricionProteicoEdadSi = 1;}
			if (is_null($request->obsidadDesnutricionProteicoFechaDiagnostico) || $request->obsidadDesnutricionProteicoFechaDiagnostico == false) {$reglasValidacion->obsidadDesnutricionProteicoFechaDiagnostico = 0;} else { $reglasValidacion->obsidadDesnutricionProteicoFechaDiagnostico = 1;}
			if (is_null($request->obsidadDesnutricionProteicoPeso) || $request->obsidadDesnutricionProteicoPeso == false) {$reglasValidacion->obsidadDesnutricionProteicoPeso = 0;} else { $reglasValidacion->obsidadDesnutricionProteicoPeso = 1;}
			if (is_null($request->obsidadDesnutricionProteicoTall) || $request->obsidadDesnutricionProteicoTall == false) {$reglasValidacion->obsidadDesnutricionProteicoTall = 0;} else { $reglasValidacion->obsidadDesnutricionProteicoTall = 1;}
			if (is_null($request->victimaMaltratoEdadMenorSiMenor) || $request->victimaMaltratoEdadMenorSiMenor == false) {$reglasValidacion->victimaMaltratoEdadMenorSiMenor = 0;} else { $reglasValidacion->victimaMaltratoEdadMenorSiMenor = 1;}
			if (is_null($request->victimaMaltratoMujerVictima) || $request->victimaMaltratoMujerVictima == false) {$reglasValidacion->victimaMaltratoMujerVictima = 0;} else { $reglasValidacion->victimaMaltratoMujerVictima = 1;}
			if (is_null($request->victimaMaltratoFechaConsultaMujerOMenorVictima) || $request->victimaMaltratoFechaConsultaMujerOMenorVictima == false) {$reglasValidacion->victimaMaltratoFechaConsultaMujerOMenorVictima = 0;} else { $reglasValidacion->victimaMaltratoFechaConsultaMujerOMenorVictima = 1;}
			if (is_null($request->victimaMaltratoEdadGeneral) || $request->victimaMaltratoEdadGeneral == false) {$reglasValidacion->victimaMaltratoEdadGeneral = 0;} else { $reglasValidacion->victimaMaltratoEdadGeneral = 1;}
			if (is_null($request->victimaViolenciaSexualFechaConsulta) || $request->victimaViolenciaSexualFechaConsulta == false) {$reglasValidacion->victimaViolenciaSexualFechaConsulta = 0;} else { $reglasValidacion->victimaViolenciaSexualFechaConsulta = 1;}
			if (is_null($request->enfermedadMentalDiagnostico) || $request->enfermedadMentalDiagnostico == false) {$reglasValidacion->enfermedadMentalDiagnostico = 0;} else { $reglasValidacion->enfermedadMentalDiagnostico = 1;}
			if (is_null($request->canverCervixGenero) || $request->canverCervixGenero == false) {$reglasValidacion->canverCervixGenero = 0;} else { $reglasValidacion->canverCervixGenero = 1;}
			if (is_null($request->pesoKilogramos) || $request->pesoKilogramos == false) {$reglasValidacion->pesoKilogramos = 0;} else { $reglasValidacion->pesoKilogramos = 1;}
			if (is_null($request->pesoFechaConsulta) || $request->pesoFechaConsulta == false) {$reglasValidacion->pesoFechaConsulta = 0;} else { $reglasValidacion->pesoFechaConsulta = 1;}
			if (is_null($request->tallaCentimetros) || $request->tallaCentimetros == false) {$reglasValidacion->tallaCentimetros = 0;} else { $reglasValidacion->tallaCentimetros = 1;}
			if (is_null($request->tallaFechaConsulta) || $request->tallaFechaConsulta == false) {$reglasValidacion->tallaFechaConsulta = 0;} else { $reglasValidacion->tallaFechaConsulta = 1;}
			if (is_null($request->fechaProbablePartoGenero) || $request->fechaProbablePartoGenero == false) {$reglasValidacion->fechaProbablePartoGenero = 0;} else { $reglasValidacion->fechaProbablePartoGenero = 1;}
			if (is_null($request->fechaProbablePartoGestacion) || $request->fechaProbablePartoGestacion == false) {$reglasValidacion->fechaProbablePartoGestacion = 0;} else { $reglasValidacion->fechaProbablePartoGestacion = 1;}
			if (is_null($request->fechaProbablePartoEdad) || $request->fechaProbablePartoEdad == false) {$reglasValidacion->fechaProbablePartoEdad = 0;} else { $reglasValidacion->fechaProbablePartoEdad = 1;}
			if (is_null($request->edadGestacionalNacerDiferenteCero) || $request->edadGestacionalNacerDiferenteCero == false) {$reglasValidacion->edadGestacionalNacerDiferenteCero = 0;} else { $reglasValidacion->edadGestacionalNacerDiferenteCero = 1;}
			if (is_null($request->edadGestacionalNacerEdad) || $request->edadGestacionalNacerEdad == false) {$reglasValidacion->edadGestacionalNacerEdad = 0;} else { $reglasValidacion->edadGestacionalNacerEdad = 1;}
			if (is_null($request->edadGestacionalNacer43Semanas) || $request->edadGestacionalNacer43Semanas == false) {$reglasValidacion->edadGestacionalNacer43Semanas = 0;} else { $reglasValidacion->edadGestacionalNacer43Semanas = 1;}
			if (is_null($request->bcgEdadDiferenteNoAplica) || $request->bcgEdadDiferenteNoAplica == false) {$reglasValidacion->bcgEdadDiferenteNoAplica = 0;} else { $reglasValidacion->bcgEdadDiferenteNoAplica = 1;}
			if (is_null($request->bcgMenor6Anios) || $request->bcgMenor6Anios == false) {$reglasValidacion->bcgMenor6Anios = 0;} else { $reglasValidacion->bcgMenor6Anios = 1;}
			if (is_null($request->bcgMayor6Anios) || $request->bcgMayor6Anios == false) {$reglasValidacion->bcgMayor6Anios = 0;} else { $reglasValidacion->bcgMayor6Anios = 1;}
			if (is_null($request->hepatitisBMenorNoAplica) || $request->hepatitisBMenorNoAplica == false) {$reglasValidacion->hepatitisBMenorNoAplica = 0;} else { $reglasValidacion->hepatitisBMenorNoAplica = 1;}
			if (is_null($request->hepatitisBMenor1AnioMenor6Anios) || $request->hepatitisBMenor1AnioMenor6Anios == false) {$reglasValidacion->hepatitisBMenor1AnioMenor6Anios = 0;} else { $reglasValidacion->hepatitisBMenor1AnioMenor6Anios = 1;}
			if (is_null($request->hepatitisBMenor1AnioMayor6Anios) || $request->hepatitisBMenor1AnioMayor6Anios == false) {$reglasValidacion->hepatitisBMenor1AnioMayor6Anios = 0;} else { $reglasValidacion->hepatitisBMenor1AnioMayor6Anios = 1;}
			if (is_null($request->pentavalenteMenor1AnioNoAplica) || $request->pentavalenteMenor1AnioNoAplica == false) {$reglasValidacion->pentavalenteMenor1AnioNoAplica = 0;} else { $reglasValidacion->pentavalenteMenor1AnioNoAplica = 1;}
			if (is_null($request->pentavalenteMenor1AnioMenor6Anios) || $request->pentavalenteMenor1AnioMenor6Anios == false) {$reglasValidacion->pentavalenteMenor1AnioMenor6Anios = 0;} else { $reglasValidacion->pentavalenteMenor1AnioMenor6Anios = 1;}
			if (is_null($request->pentavalenteMenor1AnioMayor6Anios) || $request->pentavalenteMenor1AnioMayor6Anios == false) {$reglasValidacion->pentavalenteMenor1AnioMayor6Anios = 0;} else { $reglasValidacion->pentavalenteMenor1AnioMayor6Anios = 1;}
			if (is_null($request->pentavalenteMenor4Meses) || $request->pentavalenteMenor4Meses == false) {$reglasValidacion->pentavalenteMenor4Meses = 0;} else { $reglasValidacion->pentavalenteMenor4Meses = 1;}
			if (is_null($request->pentavalenteMenor6Meses) || $request->pentavalenteMenor6Meses == false) {$reglasValidacion->pentavalenteMenor6Meses = 0;} else { $reglasValidacion->pentavalenteMenor6Meses = 1;}
			if (is_null($request->polioMenor1AnioNoAplica) || $request->polioMenor1AnioNoAplica == false) {$reglasValidacion->polioMenor1AnioNoAplica = 0;} else { $reglasValidacion->polioMenor1AnioNoAplica = 1;}
			if (is_null($request->polioMenor1AnioMenor6Anios) || $request->polioMenor1AnioMenor6Anios == false) {$reglasValidacion->polioMenor1AnioMenor6Anios = 0;} else { $reglasValidacion->polioMenor1AnioMenor6Anios = 1;}
			if (is_null($request->polioMenor1AnioMayor6Anios) || $request->polioMenor1AnioMayor6Anios == false) {$reglasValidacion->polioMenor1AnioMayor6Anios = 0;} else { $reglasValidacion->polioMenor1AnioMayor6Anios = 1;}
			if (is_null($request->polioMenor1AnioMeses) || $request->polioMenor1AnioMeses == false) {$reglasValidacion->polioMenor1AnioMeses = 0;} else { $reglasValidacion->polioMenor1AnioMeses = 1;}
			if (is_null($request->DPTMenor5AnioNoAplica) || $request->DPTMenor5AnioNoAplica == false) {$reglasValidacion->DPTMenor5AnioNoAplica = 0;} else { $reglasValidacion->DPTMenor5AnioNoAplica = 1;}
			if (is_null($request->DPTMenor5AnioMenor6Anios) || $request->DPTMenor5AnioMenor6Anios == false) {$reglasValidacion->DPTMenor5AnioMenor6Anios = 0;} else { $reglasValidacion->DPTMenor5AnioMenor6Anios = 1;}
			if (is_null($request->DPTMenor5AnioMayor6Anios) || $request->DPTMenor5AnioMayor6Anios == false) {$reglasValidacion->DPTMenor5AnioMayor6Anios = 0;} else { $reglasValidacion->DPTMenor5AnioMayor6Anios = 1;}
			if (is_null($request->DPTMenor5AnioMeses) || $request->DPTMenor5AnioMeses == false) {$reglasValidacion->DPTMenor5AnioMeses = 0;} else { $reglasValidacion->DPTMenor5AnioMeses = 1;}
			if (is_null($request->rotavirusNoAplica) || $request->rotavirusNoAplica == false) {$reglasValidacion->rotavirusNoAplica = 0;} else { $reglasValidacion->rotavirusNoAplica = 1;}
			if (is_null($request->rotavirusMenor6Anios) || $request->rotavirusMenor6Anios == false) {$reglasValidacion->rotavirusMenor6Anios = 0;} else { $reglasValidacion->rotavirusMenor6Anios = 1;}
			if (is_null($request->rotavirusMeses) || $request->rotavirusMeses == false) {$reglasValidacion->rotavirusMeses = 0;} else { $reglasValidacion->rotavirusMeses = 1;}
			if (is_null($request->neumococoNoAplica) || $request->neumococoNoAplica == false) {$reglasValidacion->neumococoNoAplica = 0;} else { $reglasValidacion->neumococoNoAplica = 1;}
			if (is_null($request->neumococoMayor6Anios) || $request->neumococoMayor6Anios == false) {$reglasValidacion->neumococoMayor6Anios = 0;} else { $reglasValidacion->neumococoMayor6Anios = 1;}
			if (is_null($request->neumococoMenor6Anios) || $request->neumococoMenor6Anios == false) {$reglasValidacion->neumococoMenor6Anios = 0;} else { $reglasValidacion->neumococoMenor6Anios = 1;}
			if (is_null($request->neumococoMeses) || $request->neumococoMeses == false) {$reglasValidacion->neumococoMeses = 0;} else { $reglasValidacion->neumococoMeses = 1;}
			if (is_null($request->influenzaNiniosNoAplica) || $request->influenzaNiniosNoAplica == false) {$reglasValidacion->influenzaNiniosNoAplica = 0;} else { $reglasValidacion->influenzaNiniosNoAplica = 1;}
			if (is_null($request->influenzaNiniosMayor6Anios) || $request->influenzaNiniosMayor6Anios == false) {$reglasValidacion->influenzaNiniosMayor6Anios = 0;} else { $reglasValidacion->influenzaNiniosMayor6Anios = 1;}
			if (is_null($request->influenzaNiniosMenor6Anios) || $request->influenzaNiniosMenor6Anios == false) {$reglasValidacion->influenzaNiniosMenor6Anios = 0;} else { $reglasValidacion->influenzaNiniosMenor6Anios = 1;}
			if (is_null($request->influenzaNiniosMeses) || $request->influenzaNiniosMeses == false) {$reglasValidacion->influenzaNiniosMeses = 0;} else { $reglasValidacion->influenzaNiniosMeses = 1;}
			if (is_null($request->fiebreAmarilla1AnioNiniosNoAplica) || $request->fiebreAmarilla1AnioNiniosNoAplica == false) {$reglasValidacion->fiebreAmarilla1AnioNiniosNoAplica = 0;} else { $reglasValidacion->fiebreAmarilla1AnioNiniosNoAplica = 1;}
			if (is_null($request->fiebreAmarilla1AnioNiniosMayor6Anios) || $request->fiebreAmarilla1AnioNiniosMayor6Anios == false) {$reglasValidacion->fiebreAmarilla1AnioNiniosMayor6Anios = 0;} else { $reglasValidacion->fiebreAmarilla1AnioNiniosMayor6Anios = 1;}
			if (is_null($request->fiebreAmarilla1AnioNiniosMenor6Anios) || $request->fiebreAmarilla1AnioNiniosMenor6Anios == false) {$reglasValidacion->fiebreAmarilla1AnioNiniosMenor6Anios = 0;} else { $reglasValidacion->fiebreAmarilla1AnioNiniosMenor6Anios = 1;}
			if (is_null($request->fiebreAmarilla1AnioNiniosMeses) || $request->fiebreAmarilla1AnioNiniosMeses == false) {$reglasValidacion->fiebreAmarilla1AnioNiniosMeses = 0;} else { $reglasValidacion->fiebreAmarilla1AnioNiniosMeses = 1;}
			if (is_null($request->hepatitisANoAplica) || $request->hepatitisANoAplica == false) {$reglasValidacion->hepatitisANoAplica = 0;} else { $reglasValidacion->hepatitisANoAplica = 1;}
			if (is_null($request->hepatitisAMayor6Anios) || $request->hepatitisAMayor6Anios == false) {$reglasValidacion->hepatitisAMayor6Anios = 0;} else { $reglasValidacion->hepatitisAMayor6Anios = 1;}
			if (is_null($request->hepatitisAMenor6Anios) || $request->hepatitisAMenor6Anios == false) {$reglasValidacion->hepatitisAMenor6Anios = 0;} else { $reglasValidacion->hepatitisAMenor6Anios = 1;}
			if (is_null($request->hepatitisAMeses) || $request->hepatitisAMeses == false) {$reglasValidacion->hepatitisAMeses = 0;} else { $reglasValidacion->hepatitisAMeses = 1;}
			if (is_null($request->tripleViralNiniosNoAplica) || $request->tripleViralNiniosNoAplica == false) {$reglasValidacion->tripleViralNiniosNoAplica = 0;} else { $reglasValidacion->tripleViralNiniosNoAplica = 1;}
			if (is_null($request->tripleViralNiniosMayor6Anios) || $request->tripleViralNiniosMayor6Anios == false) {$reglasValidacion->tripleViralNiniosMayor6Anios = 0;} else { $reglasValidacion->tripleViralNiniosMayor6Anios = 1;}
			if (is_null($request->tripleViralNiniosMenor6Anios) || $request->tripleViralNiniosMenor6Anios == false) {$reglasValidacion->tripleViralNiniosMenor6Anios = 0;} else { $reglasValidacion->tripleViralNiniosMenor6Anios = 1;}
			if (is_null($request->tripleViralNiniosMeses) || $request->tripleViralNiniosMeses == false) {$reglasValidacion->tripleViralNiniosMeses = 0;} else { $reglasValidacion->tripleViralNiniosMeses = 1;}
			if (is_null($request->VPhMayor9Anios) || $request->VPhMayor9Anios == false) {$reglasValidacion->VPhMayor9Anios = 0;} else { $reglasValidacion->VPhMayor9Anios = 1;}
			if (is_null($request->VPhGenero) || $request->VPhGenero == false) {$reglasValidacion->VPhGenero = 0;} else { $reglasValidacion->VPhGenero = 1;}
			if (is_null($request->TdOTtGenero) || $request->TdOTtGenero == false) {$reglasValidacion->TdOTtGenero = 0;} else { $reglasValidacion->TdOTtGenero = 1;}
			if (is_null($request->TdOTtMayor9Anios) || $request->TdOTtMayor9Anios == false) {$reglasValidacion->TdOTtMayor9Anios = 0;} else { $reglasValidacion->TdOTtMayor9Anios = 1;}
			if (is_null($request->placaBacterianaEdad) || $request->placaBacterianaEdad == false) {$reglasValidacion->placaBacterianaEdad = 0;} else { $reglasValidacion->placaBacterianaEdad = 1;}
			if (is_null($request->edadFechaAtencionPartoCesaria) || $request->edadFechaAtencionPartoCesaria == false) {$reglasValidacion->edadFechaAtencionPartoCesaria = 0;} else { $reglasValidacion->edadFechaAtencionPartoCesaria = 1;}
			if (is_null($request->fechaPartoGenero) || $request->fechaPartoGenero == false) {$reglasValidacion->fechaPartoGenero = 0;} else { $reglasValidacion->fechaPartoGenero = 1;}
			if (is_null($request->fechaAtencionPartoMenorFechaSalida) || $request->fechaAtencionPartoMenorFechaSalida == false) {$reglasValidacion->fechaAtencionPartoMenorFechaSalida = 0;} else { $reglasValidacion->fechaAtencionPartoMenorFechaSalida = 1;}
			if (is_null($request->fechaAtencionPartoNullFechaSalida) || $request->fechaAtencionPartoNullFechaSalida == false) {$reglasValidacion->fechaAtencionPartoNullFechaSalida = 0;} else { $reglasValidacion->fechaAtencionPartoNullFechaSalida = 1;}
			if (is_null($request->fechaPartoGestacion) || $request->fechaPartoGestacion == false) {$reglasValidacion->fechaPartoGestacion = 0;} else { $reglasValidacion->fechaPartoGestacion = 1;}
			if (is_null($request->fechaAtencionPartoVariablesExtras) || $request->fechaAtencionPartoVariablesExtras == false) {$reglasValidacion->fechaAtencionPartoVariablesExtras = 0;} else { $reglasValidacion->fechaAtencionPartoVariablesExtras = 1;}
			if (is_null($request->edadFechaSalidaAtencionPartoCesaria) || $request->edadFechaSalidaAtencionPartoCesaria == false) {$reglasValidacion->edadFechaSalidaAtencionPartoCesaria = 0;} else { $reglasValidacion->edadFechaSalidaAtencionPartoCesaria = 1;}
			if (is_null($request->fechaSalidaPartoGenero) || $request->fechaSalidaPartoGenero == false) {$reglasValidacion->fechaSalidaPartoGenero = 0;} else { $reglasValidacion->fechaSalidaPartoGenero = 1;}
			if (is_null($request->fechaSalidaPartoGestacion) || $request->fechaSalidaPartoGestacion == false) {$reglasValidacion->fechaSalidaPartoGestacion = 0;} else { $reglasValidacion->fechaSalidaPartoGestacion = 1;}
			if (is_null($request->fechaSalidaPartoMayorFechaAtencionParto) || $request->fechaSalidaPartoMayorFechaAtencionParto == false) {$reglasValidacion->fechaSalidaPartoMayorFechaAtencionParto = 0;} else { $reglasValidacion->fechaSalidaPartoMayorFechaAtencionParto = 1;}
			if (is_null($request->fechaSalidaPartoNullFechaAtencionParto) || $request->fechaSalidaPartoNullFechaAtencionParto == false) {$reglasValidacion->fechaSalidaPartoNullFechaAtencionParto = 0;} else { $reglasValidacion->fechaSalidaPartoNullFechaAtencionParto = 1;}
			if (is_null($request->fechaSalidaAtencionPartoVariablesExtras) || $request->fechaSalidaAtencionPartoVariablesExtras == false) {$reglasValidacion->fechaSalidaAtencionPartoVariablesExtras = 0;} else { $reglasValidacion->fechaSalidaAtencionPartoVariablesExtras = 1;}
			if (is_null($request->edadFechaConsejeriaLactanciaMaternaDiferente1885) || $request->edadFechaConsejeriaLactanciaMaternaDiferente1885 == false) {$reglasValidacion->edadFechaConsejeriaLactanciaMaternaDiferente1885 = 0;} else { $reglasValidacion->edadFechaConsejeriaLactanciaMaternaDiferente1885 = 1;}
			if (is_null($request->fechaConsejeriaLactanciaMaternaGenero) || $request->fechaConsejeriaLactanciaMaternaGenero == false) {$reglasValidacion->fechaConsejeriaLactanciaMaternaGenero = 0;} else { $reglasValidacion->fechaConsejeriaLactanciaMaternaGenero = 1;}
			if (is_null($request->edadFechaControlRecienNacidoDiferente1885) || $request->edadFechaControlRecienNacidoDiferente1885 == false) {$reglasValidacion->edadFechaControlRecienNacidoDiferente1885 = 0;} else { $reglasValidacion->edadFechaControlRecienNacidoDiferente1885 = 1;}
			if (is_null($request->edadFechaPlanificacionFamiliarPrimeraVez) || $request->edadFechaPlanificacionFamiliarPrimeraVez == false) {$reglasValidacion->edadFechaPlanificacionFamiliarPrimeraVez = 0;} else { $reglasValidacion->edadFechaPlanificacionFamiliarPrimeraVez = 1;}
			if (is_null($request->suministroMetodoAnticonseptivoFechaSuministro) || $request->suministroMetodoAnticonseptivoFechaSuministro == false) {$reglasValidacion->suministroMetodoAnticonseptivoFechaSuministro = 0;} else { $reglasValidacion->suministroMetodoAnticonseptivoFechaSuministro = 1;}
			if (is_null($request->suministroMetodoAnticonseptivoEdad) || $request->suministroMetodoAnticonseptivoEdad == false) {$reglasValidacion->suministroMetodoAnticonseptivoEdad = 0;} else { $reglasValidacion->suministroMetodoAnticonseptivoEdad = 1;}
			if (is_null($request->fechaSuministroMetodoAnticonceptivoSMA) || $request->fechaSuministroMetodoAnticonceptivoSMA == false) {$reglasValidacion->fechaSuministroMetodoAnticonceptivoSMA = 0;} else { $reglasValidacion->fechaSuministroMetodoAnticonceptivoSMA = 1;}
			if (is_null($request->fechaSuministroMetodoAnticonceptivoPFPV) || $request->fechaSuministroMetodoAnticonceptivoPFPV == false) {$reglasValidacion->fechaSuministroMetodoAnticonceptivoPFPV = 0;} else { $reglasValidacion->fechaSuministroMetodoAnticonceptivoPFPV = 1;}
			if (is_null($request->controlPrenatalPrimeraVezEdad) || $request->controlPrenatalPrimeraVezEdad == false) {$reglasValidacion->controlPrenatalPrimeraVezEdad = 0;} else { $reglasValidacion->controlPrenatalPrimeraVezEdad = 1;}
			if (is_null($request->controlPrenatalPrimeraVezGenero) || $request->controlPrenatalPrimeraVezGenero == false) {$reglasValidacion->controlPrenatalPrimeraVezGenero = 0;} else { $reglasValidacion->controlPrenatalPrimeraVezGenero = 1;}
			if (is_null($request->controlPrenatalPrimeraVezGestacion) || $request->controlPrenatalPrimeraVezGestacion == false) {$reglasValidacion->controlPrenatalPrimeraVezGestacion = 0;} else { $reglasValidacion->controlPrenatalPrimeraVezGestacion = 1;}
			if (is_null($request->controlPrenatalPrimeraVezMenorUCP) || $request->controlPrenatalPrimeraVezMenorUCP == false) {$reglasValidacion->controlPrenatalPrimeraVezMenorUCP = 0;} else { $reglasValidacion->controlPrenatalPrimeraVezMenorUCP = 1;}
			if (is_null($request->edadControlPrenatalPrimeraVez) || $request->edadControlPrenatalPrimeraVez == false) {$reglasValidacion->edadControlPrenatalPrimeraVez = 0;} else { $reglasValidacion->edadControlPrenatalPrimeraVez = 1;}
			if (is_null($request->controlPrenatalEdad) || $request->controlPrenatalEdad == false) {$reglasValidacion->controlPrenatalEdad = 0;} else { $reglasValidacion->controlPrenatalEdad = 1;}
			if (is_null($request->controlPrenatalControles) || $request->controlPrenatalControles == false) {$reglasValidacion->controlPrenatalControles = 0;} else { $reglasValidacion->controlPrenatalControles = 1;}
			if (is_null($request->edadControlPrenatal) || $request->edadControlPrenatal == false) {$reglasValidacion->edadControlPrenatal = 0;} else { $reglasValidacion->edadControlPrenatal = 1;}
			if (is_null($request->controlPrenatalGenero) || $request->controlPrenatalGenero == false) {$reglasValidacion->controlPrenatalGenero = 0;} else { $reglasValidacion->controlPrenatalGenero = 1;}
			if (is_null($request->controlPrenatalGestacion) || $request->controlPrenatalGestacion == false) {$reglasValidacion->controlPrenatalGestacion = 0;} else { $reglasValidacion->controlPrenatalGestacion = 1;}
			if (is_null($request->fechaUltimoControlPrenatalEdad) || $request->fechaUltimoControlPrenatalEdad == false) {$reglasValidacion->fechaUltimoControlPrenatalEdad = 0;} else { $reglasValidacion->fechaUltimoControlPrenatalEdad = 1;}
			if (is_null($request->fechaUltimoControlPrenatalControlPrenatalPrimeraVez) || $request->fechaUltimoControlPrenatalControlPrenatalPrimeraVez == false) {$reglasValidacion->fechaUltimoControlPrenatalControlPrenatalPrimeraVez = 0;} else { $reglasValidacion->fechaUltimoControlPrenatalControlPrenatalPrimeraVez = 1;}
			if (is_null($request->edadFechaUltimoControlPrenatal) || $request->edadFechaUltimoControlPrenatal == false) {$reglasValidacion->edadFechaUltimoControlPrenatal = 0;} else { $reglasValidacion->edadFechaUltimoControlPrenatal = 1;}
			if (is_null($request->ultimoControlPrenatalGenero) || $request->ultimoControlPrenatalGenero == false) {$reglasValidacion->ultimoControlPrenatalGenero = 0;} else { $reglasValidacion->ultimoControlPrenatalGenero = 1;}
			if (is_null($request->ultimoControlPrenatalGestacion) || $request->ultimoControlPrenatalGestacion == false) {$reglasValidacion->ultimoControlPrenatalGestacion = 0;} else { $reglasValidacion->ultimoControlPrenatalGestacion = 1;}
			if (is_null($request->suministroAcidoFolicoUltimoControlPrenatalEdad) || $request->suministroAcidoFolicoUltimoControlPrenatalEdad == false) {$reglasValidacion->suministroAcidoFolicoUltimoControlPrenatalEdad = 0;} else { $reglasValidacion->suministroAcidoFolicoUltimoControlPrenatalEdad = 1;}
			if (is_null($request->edadSuministroAcidoFolicoUltimoControlPrenatal) || $request->edadSuministroAcidoFolicoUltimoControlPrenatal == false) {$reglasValidacion->edadSuministroAcidoFolicoUltimoControlPrenatal = 0;} else { $reglasValidacion->edadSuministroAcidoFolicoUltimoControlPrenatal = 1;}
			if (is_null($request->suministroAcidoFolicoUCPGenero) || $request->suministroAcidoFolicoUCPGenero == false) {$reglasValidacion->suministroAcidoFolicoUCPGenero = 0;} else { $reglasValidacion->suministroAcidoFolicoUCPGenero = 1;}
			if (is_null($request->suministroAcidoFolicoUcpGestacion) || $request->suministroAcidoFolicoUcpGestacion == false) {$reglasValidacion->suministroAcidoFolicoUcpGestacion = 0;} else { $reglasValidacion->suministroAcidoFolicoUcpGestacion = 1;}
			if (is_null($request->sulfatoFerrosoUltimoControlPrenatalEdad) || $request->sulfatoFerrosoUltimoControlPrenatalEdad == false) {$reglasValidacion->sulfatoFerrosoUltimoControlPrenatalEdad = 0;} else { $reglasValidacion->sulfatoFerrosoUltimoControlPrenatalEdad = 1;}
			if (is_null($request->edadSulfatoFerrosoUltimoControlPrenatal) || $request->edadSulfatoFerrosoUltimoControlPrenatal == false) {$reglasValidacion->edadSulfatoFerrosoUltimoControlPrenatal = 0;} else { $reglasValidacion->edadSulfatoFerrosoUltimoControlPrenatal = 1;}
			if (is_null($request->suministroSulfatoFerrosoUCPGenero) || $request->suministroSulfatoFerrosoUCPGenero == false) {$reglasValidacion->suministroSulfatoFerrosoUCPGenero = 0;} else { $reglasValidacion->suministroSulfatoFerrosoUCPGenero = 1;}
			if (is_null($request->suministroSulfatoFerrosoUcpGestacion) || $request->suministroSulfatoFerrosoUcpGestacion == false) {$reglasValidacion->suministroSulfatoFerrosoUcpGestacion = 0;} else { $reglasValidacion->suministroSulfatoFerrosoUcpGestacion = 1;}
			if (is_null($request->carbonatoCalcioUltimoControlPrenatalEdad) || $request->carbonatoCalcioUltimoControlPrenatalEdad == false) {$reglasValidacion->carbonatoCalcioUltimoControlPrenatalEdad = 0;} else { $reglasValidacion->carbonatoCalcioUltimoControlPrenatalEdad = 1;}
			if (is_null($request->edadCarbonatoCalcioUltimoControlPrenatal) || $request->edadCarbonatoCalcioUltimoControlPrenatal == false) {$reglasValidacion->edadCarbonatoCalcioUltimoControlPrenatal = 0;} else { $reglasValidacion->edadCarbonatoCalcioUltimoControlPrenatal = 1;}
			if (is_null($request->suministroCarbonatoCalcioUCPGenero) || $request->suministroCarbonatoCalcioUCPGenero == false) {$reglasValidacion->suministroCarbonatoCalcioUCPGenero = 0;} else { $reglasValidacion->suministroCarbonatoCalcioUCPGenero = 1;}
			if (is_null($request->suministroCarbonatoCalcioGestacion) || $request->suministroCarbonatoCalcioGestacion == false) {$reglasValidacion->suministroCarbonatoCalcioGestacion = 0;} else { $reglasValidacion->suministroCarbonatoCalcioGestacion = 1;}
			if (is_null($request->fechaDiagnosticoDesnutricionProteicoCaloricaObesidad) || $request->fechaDiagnosticoDesnutricionProteicoCaloricaObesidad == false) {$reglasValidacion->fechaDiagnosticoDesnutricionProteicoCaloricaObesidad = 0;} else { $reglasValidacion->fechaDiagnosticoDesnutricionProteicoCaloricaObesidad = 1;}
			if (is_null($request->fechaDiagnosticoDesnutricionProteicoCaloricaPeso) || $request->fechaDiagnosticoDesnutricionProteicoCaloricaPeso == false) {$reglasValidacion->fechaDiagnosticoDesnutricionProteicoCaloricaPeso = 0;} else { $reglasValidacion->fechaDiagnosticoDesnutricionProteicoCaloricaPeso = 1;}
			if (is_null($request->fechaDiagnosticoDesnutricionProteicoCaloricaTalla) || $request->fechaDiagnosticoDesnutricionProteicoCaloricaTalla == false) {$reglasValidacion->fechaDiagnosticoDesnutricionProteicoCaloricaTalla = 0;} else { $reglasValidacion->fechaDiagnosticoDesnutricionProteicoCaloricaTalla = 1;}
			if (is_null($request->fechaConsultaMujerMenorVictimaMaltrato) || $request->fechaConsultaMujerMenorVictimaMaltrato == false) {$reglasValidacion->fechaConsultaMujerMenorVictimaMaltrato = 0;} else { $reglasValidacion->fechaConsultaMujerMenorVictimaMaltrato = 1;}
			if (is_null($request->fechaConsultaVictimaViolenciaSexual) || $request->fechaConsultaVictimaViolenciaSexual == false) {$reglasValidacion->fechaConsultaVictimaViolenciaSexual = 0;} else { $reglasValidacion->fechaConsultaVictimaViolenciaSexual = 1;}
			if (is_null($request->edadFechaConsultaCrecimientoDesarrolloPrimeraVez) || $request->edadFechaConsultaCrecimientoDesarrolloPrimeraVez == false) {$reglasValidacion->edadFechaConsultaCrecimientoDesarrolloPrimeraVez = 0;} else { $reglasValidacion->edadFechaConsultaCrecimientoDesarrolloPrimeraVez = 1;}
			if (is_null($request->edadFechaSuministroSulfatoFerrosoUltimaConsultaMenor10Anios) || $request->edadFechaSuministroSulfatoFerrosoUltimaConsultaMenor10Anios == false) {$reglasValidacion->edadFechaSuministroSulfatoFerrosoUltimaConsultaMenor10Anios = 0;} else { $reglasValidacion->edadFechaSuministroSulfatoFerrosoUltimaConsultaMenor10Anios = 1;}
			if (is_null($request->suministroSulfatoFerrosoUltimaConsultaMenor10AniosEdad) || $request->suministroSulfatoFerrosoUltimaConsultaMenor10AniosEdad == false) {$reglasValidacion->suministroSulfatoFerrosoUltimaConsultaMenor10AniosEdad = 0;} else { $reglasValidacion->suministroSulfatoFerrosoUltimaConsultaMenor10AniosEdad = 1;}
			if (is_null($request->edadFechaSuministroVitaminaAUltimaConsultaMenor10AniosDiferente0) || $request->edadFechaSuministroVitaminaAUltimaConsultaMenor10AniosDiferente0 == false) {$reglasValidacion->edadFechaSuministroVitaminaAUltimaConsultaMenor10AniosDiferente0 = 0;} else { $reglasValidacion->edadFechaSuministroVitaminaAUltimaConsultaMenor10AniosDiferente0 = 1;}
			if (is_null($request->suministroVitaminaAUltimaConsultaMenor10AniosEdad) || $request->suministroVitaminaAUltimaConsultaMenor10AniosEdad == false) {$reglasValidacion->suministroVitaminaAUltimaConsultaMenor10AniosEdad = 0;} else { $reglasValidacion->suministroVitaminaAUltimaConsultaMenor10AniosEdad = 1;}
			if (is_null($request->consultaJovenPrimeraVezEdad) || $request->consultaJovenPrimeraVezEdad == false) {$reglasValidacion->consultaJovenPrimeraVezEdad = 0;} else { $reglasValidacion->consultaJovenPrimeraVezEdad = 1;}
			if (is_null($request->edadConsultaJovenPrimeraVez) || $request->edadConsultaJovenPrimeraVez == false) {$reglasValidacion->edadConsultaJovenPrimeraVez = 0;} else { $reglasValidacion->edadConsultaJovenPrimeraVez = 1;}
			if (is_null($request->consultaAdultoPrimeraVezEdad) || $request->consultaAdultoPrimeraVezEdad == false) {$reglasValidacion->consultaAdultoPrimeraVezEdad = 0;} else { $reglasValidacion->consultaAdultoPrimeraVezEdad = 1;}
			if (is_null($request->edadConsultaAdultoPrimeraVez) || $request->edadConsultaAdultoPrimeraVez == false) {$reglasValidacion->edadConsultaAdultoPrimeraVez = 0;} else { $reglasValidacion->edadConsultaAdultoPrimeraVez = 1;}
			if (is_null($request->consultaAdultoPrimeraVezRangosEdad) || $request->consultaAdultoPrimeraVezRangosEdad == false) {$reglasValidacion->consultaAdultoPrimeraVezRangosEdad = 0;} else { $reglasValidacion->consultaAdultoPrimeraVezRangosEdad = 1;}
			if (is_null($request->preservativosEntregadosPacConITS) || $request->preservativosEntregadosPacConITS == false) {$reglasValidacion->preservativosEntregadosPacConITS = 0;} else { $reglasValidacion->preservativosEntregadosPacConITS = 1;}
			if (is_null($request->asesoriaPreTestElisaVIHMenorPostAsesoriaMismoTest) || $request->asesoriaPreTestElisaVIHMenorPostAsesoriaMismoTest == false) {$reglasValidacion->asesoriaPreTestElisaVIHMenorPostAsesoriaMismoTest = 0;} else { $reglasValidacion->asesoriaPreTestElisaVIHMenorPostAsesoriaMismoTest = 1;}
			if (is_null($request->asesoriaPreTestElisaVIHMenorFechaTomaTest) || $request->asesoriaPreTestElisaVIHMenorFechaTomaTest == false) {$reglasValidacion->asesoriaPreTestElisaVIHMenorFechaTomaTest = 0;} else { $reglasValidacion->asesoriaPreTestElisaVIHMenorFechaTomaTest = 1;}
			if (is_null($request->asesoriaPostTestMayorPreAsesoriaMismoTest) || $request->asesoriaPostTestMayorPreAsesoriaMismoTest == false) {$reglasValidacion->asesoriaPostTestMayorPreAsesoriaMismoTest = 0;} else { $reglasValidacion->asesoriaPostTestMayorPreAsesoriaMismoTest = 1;}
			if (is_null($request->asesoriaPostTestElisaVIHMayorFechaTomaTest) || $request->asesoriaPostTestElisaVIHMayorFechaTomaTest == false) {$reglasValidacion->asesoriaPostTestElisaVIHMayorFechaTomaTest = 0;} else { $reglasValidacion->asesoriaPostTestElisaVIHMayorFechaTomaTest = 1;}
			if (is_null($request->diagnosticoPacienteEnfermedadMental) || $request->diagnosticoPacienteEnfermedadMental == false) {$reglasValidacion->diagnosticoPacienteEnfermedadMental = 0;} else { $reglasValidacion->diagnosticoPacienteEnfermedadMental = 1;}
			if (is_null($request->fechaAntigenoSuperficieHepatitisBGestantesEdad) || $request->fechaAntigenoSuperficieHepatitisBGestantesEdad == false) {$reglasValidacion->fechaAntigenoSuperficieHepatitisBGestantesEdad = 0;} else { $reglasValidacion->fechaAntigenoSuperficieHepatitisBGestantesEdad = 1;}
			if (is_null($request->fechaAntigenoSuperficieHepatitisBGestantesResultado) || $request->fechaAntigenoSuperficieHepatitisBGestantesResultado == false) {$reglasValidacion->fechaAntigenoSuperficieHepatitisBGestantesResultado = 0;} else { $reglasValidacion->fechaAntigenoSuperficieHepatitisBGestantesResultado = 1;}
			if (is_null($request->fechaAntigenoSuperficieHepatitisBGestantesGenero) || $request->fechaAntigenoSuperficieHepatitisBGestantesGenero == false) {$reglasValidacion->fechaAntigenoSuperficieHepatitisBGestantesGenero = 0;} else { $reglasValidacion->fechaAntigenoSuperficieHepatitisBGestantesGenero = 1;}
			if (is_null($request->fechaAntigenoSuperficieHepatitisBGestantesGestacion) || $request->fechaAntigenoSuperficieHepatitisBGestantesGestacion == false) {$reglasValidacion->fechaAntigenoSuperficieHepatitisBGestantesGestacion = 0;} else { $reglasValidacion->fechaAntigenoSuperficieHepatitisBGestantesGestacion = 1;}
			if (is_null($request->resultadoAntigenoSuperficieHepatitisBGestantesEdad) || $request->resultadoAntigenoSuperficieHepatitisBGestantesEdad == false) {$reglasValidacion->resultadoAntigenoSuperficieHepatitisBGestantesEdad = 0;} else { $reglasValidacion->resultadoAntigenoSuperficieHepatitisBGestantesEdad = 1;}
			if (is_null($request->resultadoAntigenoSuperficieHepatitisBGestantesFechaAntigeno) || $request->resultadoAntigenoSuperficieHepatitisBGestantesFechaAntigeno == false) {$reglasValidacion->resultadoAntigenoSuperficieHepatitisBGestantesFechaAntigeno = 0;} else { $reglasValidacion->resultadoAntigenoSuperficieHepatitisBGestantesFechaAntigeno = 1;}
			if (is_null($request->resultadoAntigenoSuperficieHepatitisBGestantesGenero) || $request->resultadoAntigenoSuperficieHepatitisBGestantesGenero == false) {$reglasValidacion->resultadoAntigenoSuperficieHepatitisBGestantesGenero = 0;} else { $reglasValidacion->resultadoAntigenoSuperficieHepatitisBGestantesGenero = 1;}
			if (is_null($request->resultadoAntigenoSuperficieHepatitisBGestantesGestacion) || $request->resultadoAntigenoSuperficieHepatitisBGestantesGestacion == false) {$reglasValidacion->resultadoAntigenoSuperficieHepatitisBGestantesGestacion = 0;} else { $reglasValidacion->resultadoAntigenoSuperficieHepatitisBGestantesGestacion = 1;}
			if (is_null($request->fechaSerologiaSifilisResultadoSerologiaSifilis) || $request->fechaSerologiaSifilisResultadoSerologiaSifilis == false) {$reglasValidacion->fechaSerologiaSifilisResultadoSerologiaSifilis = 0;} else { $reglasValidacion->fechaSerologiaSifilisResultadoSerologiaSifilis = 1;}
			if (is_null($request->resultadoSerologiaSifilisFechaSerologiaSifilis) || $request->resultadoSerologiaSifilisFechaSerologiaSifilis == false) {$reglasValidacion->resultadoSerologiaSifilisFechaSerologiaSifilis = 0;} else { $reglasValidacion->resultadoSerologiaSifilisFechaSerologiaSifilis = 1;}
			if (is_null($request->fechaTomaElisaVIHResultadoElisaVIH) || $request->fechaTomaElisaVIHResultadoElisaVIH == false) {$reglasValidacion->fechaTomaElisaVIHResultadoElisaVIH = 0;} else { $reglasValidacion->fechaTomaElisaVIHResultadoElisaVIH = 1;}
			if (is_null($request->fechaTomaElisaVIHMayorFechaAsesoriaPreTest) || $request->fechaTomaElisaVIHMayorFechaAsesoriaPreTest == false) {$reglasValidacion->fechaTomaElisaVIHMayorFechaAsesoriaPreTest = 0;} else { $reglasValidacion->fechaTomaElisaVIHMayorFechaAsesoriaPreTest = 1;}
			if (is_null($request->fechaTomaElisaVIHMayorFechaAsesoriaPostTest) || $request->fechaTomaElisaVIHMayorFechaAsesoriaPostTest == false) {$reglasValidacion->fechaTomaElisaVIHMayorFechaAsesoriaPostTest = 0;} else { $reglasValidacion->fechaTomaElisaVIHMayorFechaAsesoriaPostTest = 1;}
			if (is_null($request->resultadoElisaVIHFechaTomaTest) || $request->resultadoElisaVIHFechaTomaTest == false) {$reglasValidacion->resultadoElisaVIHFechaTomaTest = 0;} else { $reglasValidacion->resultadoElisaVIHFechaTomaTest = 1;}
			if (is_null($request->fechaTSHNeonatalResultadoTest) || $request->fechaTSHNeonatalResultadoTest == false) {$reglasValidacion->fechaTSHNeonatalResultadoTest = 0;} else { $reglasValidacion->fechaTSHNeonatalResultadoTest = 1;}
			if (is_null($request->resultadoTSHNeonatalFechaTomaTest) || $request->resultadoTSHNeonatalFechaTomaTest == false) {$reglasValidacion->resultadoTSHNeonatalFechaTomaTest = 0;} else { $reglasValidacion->resultadoTSHNeonatalFechaTomaTest = 1;}
			if (is_null($request->fechaTamizajeCancerCuelloUterinoDiferenteCero) || $request->fechaTamizajeCancerCuelloUterinoDiferenteCero == false) {$reglasValidacion->fechaTamizajeCancerCuelloUterinoDiferenteCero = 0;} else { $reglasValidacion->fechaTamizajeCancerCuelloUterinoDiferenteCero = 1;}
			if (is_null($request->tamizajeCancerCuelloUterinoGenero) || $request->tamizajeCancerCuelloUterinoGenero == false) {$reglasValidacion->tamizajeCancerCuelloUterinoGenero = 0;} else { $reglasValidacion->tamizajeCancerCuelloUterinoGenero = 1;}
			if (is_null($request->edadFechaCitologiaCervicoUterina1845) || $request->edadFechaCitologiaCervicoUterina1845 == false) {$reglasValidacion->edadFechaCitologiaCervicoUterina1845 = 0;} else { $reglasValidacion->edadFechaCitologiaCervicoUterina1845 = 1;}
			if (is_null($request->citologiaCervicoUterinaGenero) || $request->citologiaCervicoUterinaGenero == false) {$reglasValidacion->citologiaCervicoUterinaGenero = 0;} else { $reglasValidacion->citologiaCervicoUterinaGenero = 1;}
			if (is_null($request->fechaCalidadMuestraCitologiaCervicouterinaBethesdaDiferenteCero) || $request->fechaCalidadMuestraCitologiaCervicouterinaBethesdaDiferenteCero == false) {$reglasValidacion->fechaCalidadMuestraCitologiaCervicouterinaBethesdaDiferenteCero = 0;} else { $reglasValidacion->fechaCalidadMuestraCitologiaCervicouterinaBethesdaDiferenteCero = 1;}
			if (is_null($request->resultadoCitologiaCervicoUterinaFechaCitologia) || $request->resultadoCitologiaCervicoUterinaFechaCitologia == false) {$reglasValidacion->resultadoCitologiaCervicoUterinaFechaCitologia = 0;} else { $reglasValidacion->resultadoCitologiaCervicoUterinaFechaCitologia = 1;}
			if (is_null($request->citologiaCervicoUterinaSegunBethesdaGenero) || $request->citologiaCervicoUterinaSegunBethesdaGenero == false) {$reglasValidacion->citologiaCervicoUterinaSegunBethesdaGenero = 0;} else { $reglasValidacion->citologiaCervicoUterinaSegunBethesdaGenero = 1;}
			if (is_null($request->fechaCalidadMuestraCitologiaCervicouterinaDiferenteCero) || $request->fechaCalidadMuestraCitologiaCervicouterinaDiferenteCero == false) {$reglasValidacion->fechaCalidadMuestraCitologiaCervicouterinaDiferenteCero = 0;} else { $reglasValidacion->fechaCalidadMuestraCitologiaCervicouterinaDiferenteCero = 1;}
			if (is_null($request->calidadMuestraCitologiaCervicouterinaResultados) || $request->calidadMuestraCitologiaCervicouterinaResultados == false) {$reglasValidacion->calidadMuestraCitologiaCervicouterinaResultados = 0;} else { $reglasValidacion->calidadMuestraCitologiaCervicouterinaResultados = 1;}
			if (is_null($request->calidadMuestraCitologiaCervicoUterinaGenero) || $request->calidadMuestraCitologiaCervicoUterinaGenero == false) {$reglasValidacion->calidadMuestraCitologiaCervicoUterinaGenero = 0;} else { $reglasValidacion->calidadMuestraCitologiaCervicoUterinaGenero = 1;}
			if (is_null($request->fechaCodigoHabilitacionIpsCitologiaCervicouterina) || $request->fechaCodigoHabilitacionIpsCitologiaCervicouterina == false) {$reglasValidacion->fechaCodigoHabilitacionIpsCitologiaCervicouterina = 0;} else { $reglasValidacion->fechaCodigoHabilitacionIpsCitologiaCervicouterina = 1;}
			if (is_null($request->codigoIpsTomaCitologiaCervicoUterinaGenero) || $request->codigoIpsTomaCitologiaCervicoUterinaGenero == false) {$reglasValidacion->codigoIpsTomaCitologiaCervicoUterinaGenero = 0;} else { $reglasValidacion->codigoIpsTomaCitologiaCervicoUterinaGenero = 1;}
			if (is_null($request->codigoIpsTomaCitologiaCervicoUterinaMuestraTest) || $request->codigoIpsTomaCitologiaCervicoUterinaMuestraTest == false) {$reglasValidacion->codigoIpsTomaCitologiaCervicoUterinaMuestraTest = 0;} else { $reglasValidacion->codigoIpsTomaCitologiaCervicoUterinaMuestraTest = 1;}
			if (is_null($request->edadFechaColposcopia) || $request->edadFechaColposcopia == false) {$reglasValidacion->edadFechaColposcopia = 0;} else { $reglasValidacion->edadFechaColposcopia = 1;}
			if (is_null($request->fechacolposcopiaGenero) || $request->fechacolposcopiaGenero == false) {$reglasValidacion->fechacolposcopiaGenero = 0;} else { $reglasValidacion->fechacolposcopiaGenero = 1;}
			if (is_null($request->fechacolposcopiaCodigoIpsTomaTest) || $request->fechacolposcopiaCodigoIpsTomaTest == false) {$reglasValidacion->fechacolposcopiaCodigoIpsTomaTest = 0;} else { $reglasValidacion->fechacolposcopiaCodigoIpsTomaTest = 1;}
			if (is_null($request->codigoHabilitacionIPSColposcopiaDB) || $request->codigoHabilitacionIPSColposcopiaDB == false) {$reglasValidacion->codigoHabilitacionIPSColposcopiaDB = 0;} else { $reglasValidacion->codigoHabilitacionIPSColposcopiaDB = 1;}
			if (is_null($request->fechaCodigoHabilitacionIPSColposcopia) || $request->fechaCodigoHabilitacionIPSColposcopia == false) {$reglasValidacion->fechaCodigoHabilitacionIPSColposcopia = 0;} else { $reglasValidacion->fechaCodigoHabilitacionIPSColposcopia = 1;}
			if (is_null($request->codigoIpsTomaColposcopiaGenero) || $request->codigoIpsTomaColposcopiaGenero == false) {$reglasValidacion->codigoIpsTomaColposcopiaGenero = 0;} else { $reglasValidacion->codigoIpsTomaColposcopiaGenero = 1;}
			if (is_null($request->codigoIpsTomaColposcopiaFechaColposcopia) || $request->codigoIpsTomaColposcopiaFechaColposcopia == false) {$reglasValidacion->codigoIpsTomaColposcopiaFechaColposcopia = 0;} else { $reglasValidacion->codigoIpsTomaColposcopiaFechaColposcopia = 1;}
			if (is_null($request->edadFechaBiopsiaCervical) || $request->edadFechaBiopsiaCervical == false) {$reglasValidacion->edadFechaBiopsiaCervical = 0;} else { $reglasValidacion->edadFechaBiopsiaCervical = 1;}
			if (is_null($request->fechaBiopsiaCervicalGenero) || $request->fechaBiopsiaCervicalGenero == false) {$reglasValidacion->fechaBiopsiaCervicalGenero = 0;} else { $reglasValidacion->fechaBiopsiaCervicalGenero = 1;}
			if (is_null($request->fechaBiopsiaCervicalResultadoTest) || $request->fechaBiopsiaCervicalResultadoTest == false) {$reglasValidacion->fechaBiopsiaCervicalResultadoTest = 0;} else { $reglasValidacion->fechaBiopsiaCervicalResultadoTest = 1;}
			if (is_null($request->fechaResultadoBiopsiaCervical) || $request->fechaResultadoBiopsiaCervical == false) {$reglasValidacion->fechaResultadoBiopsiaCervical = 0;} else { $reglasValidacion->fechaResultadoBiopsiaCervical = 1;}
			if (is_null($request->resultadoBiopsiaCervicalGenero) || $request->resultadoBiopsiaCervicalGenero == false) {$reglasValidacion->resultadoBiopsiaCervicalGenero = 0;} else { $reglasValidacion->resultadoBiopsiaCervicalGenero = 1;}
			if (is_null($request->resultadoBiopsiaCervicalFechaTest) || $request->resultadoBiopsiaCervicalFechaTest == false) {$reglasValidacion->resultadoBiopsiaCervicalFechaTest = 0;} else { $reglasValidacion->resultadoBiopsiaCervicalFechaTest = 1;}
			if (is_null($request->codigoHabilitacionIpsBiopsiaCervicalDB) || $request->codigoHabilitacionIpsBiopsiaCervicalDB == false) {$reglasValidacion->codigoHabilitacionIpsBiopsiaCervicalDB = 0;} else { $reglasValidacion->codigoHabilitacionIpsBiopsiaCervicalDB = 1;}
			if (is_null($request->fechaCodigoHabilitacionIpsBiopsiaCervical) || $request->fechaCodigoHabilitacionIpsBiopsiaCervical == false) {$reglasValidacion->fechaCodigoHabilitacionIpsBiopsiaCervical = 0;} else { $reglasValidacion->fechaCodigoHabilitacionIpsBiopsiaCervical = 1;}
			if (is_null($request->codigoIpsTomaBiopsiaCervicalGenero) || $request->codigoIpsTomaBiopsiaCervicalGenero == false) {$reglasValidacion->codigoIpsTomaBiopsiaCervicalGenero = 0;} else { $reglasValidacion->codigoIpsTomaBiopsiaCervicalGenero = 1;}
			if (is_null($request->codigoIpsTomaBiopsiaCervicalResultadoTest) || $request->codigoIpsTomaBiopsiaCervicalResultadoTest == false) {$reglasValidacion->codigoIpsTomaBiopsiaCervicalResultadoTest = 0;} else { $reglasValidacion->codigoIpsTomaBiopsiaCervicalResultadoTest = 1;}
			if (is_null($request->fechaMamografiaGenero) || $request->fechaMamografiaGenero == false) {$reglasValidacion->fechaMamografiaGenero = 0;} else { $reglasValidacion->fechaMamografiaGenero = 1;}
			if (is_null($request->fechaMamografia) || $request->fechaMamografia == false) {$reglasValidacion->fechaMamografia = 0;} else { $reglasValidacion->fechaMamografia = 1;}
			if (is_null($request->fechaMamografiaEdad) || $request->fechaMamografiaEdad == false) {$reglasValidacion->fechaMamografiaEdad = 0;} else { $reglasValidacion->fechaMamografiaEdad = 1;}
			if (is_null($request->fechaResultadoMamografia) || $request->fechaResultadoMamografia == false) {$reglasValidacion->fechaResultadoMamografia = 0;} else { $reglasValidacion->fechaResultadoMamografia = 1;}
			if (is_null($request->resultadoMamografiaGenero) || $request->resultadoMamografiaGenero == false) {$reglasValidacion->resultadoMamografiaGenero = 0;} else { $reglasValidacion->resultadoMamografiaGenero = 1;}
			if (is_null($request->resultadoMamografiaFechaEdad) || $request->resultadoMamografiaFechaEdad == false) {$reglasValidacion->resultadoMamografiaFechaEdad = 0;} else { $reglasValidacion->resultadoMamografiaFechaEdad = 1;}
			if (is_null($request->resultadoMamografiaFechaTest) || $request->resultadoMamografiaFechaTest == false) {$reglasValidacion->resultadoMamografiaFechaTest = 0;} else { $reglasValidacion->resultadoMamografiaFechaTest = 1;}
			if (is_null($request->codigoHabilitacionIPSTomaMamografiaDB) || $request->codigoHabilitacionIPSTomaMamografiaDB == false) {$reglasValidacion->codigoHabilitacionIPSTomaMamografiaDB = 0;} else { $reglasValidacion->codigoHabilitacionIPSTomaMamografiaDB = 1;}
			if (is_null($request->fechaCodigoHabilitacionIPSTomaMamografia) || $request->fechaCodigoHabilitacionIPSTomaMamografia == false) {$reglasValidacion->fechaCodigoHabilitacionIPSTomaMamografia = 0;} else { $reglasValidacion->fechaCodigoHabilitacionIPSTomaMamografia = 1;}
			if (is_null($request->codigoIpsTomaMamografiaGenero) || $request->codigoIpsTomaMamografiaGenero == false) {$reglasValidacion->codigoIpsTomaMamografiaGenero = 0;} else { $reglasValidacion->codigoIpsTomaMamografiaGenero = 1;}
			if (is_null($request->codigoIpsTomaMamografiaEdad) || $request->codigoIpsTomaMamografiaEdad == false) {$reglasValidacion->codigoIpsTomaMamografiaEdad = 0;} else { $reglasValidacion->codigoIpsTomaMamografiaEdad = 1;}
			if (is_null($request->codigoIpsTomaMamografiaResultadoTest) || $request->codigoIpsTomaMamografiaResultadoTest == false) {$reglasValidacion->codigoIpsTomaMamografiaResultadoTest = 0;} else { $reglasValidacion->codigoIpsTomaMamografiaResultadoTest = 1;}
			if (is_null($request->fechatomaBiopsiaSenoBACAFGenero) || $request->fechatomaBiopsiaSenoBACAFGenero == false) {$reglasValidacion->fechatomaBiopsiaSenoBACAFGenero = 0;} else { $reglasValidacion->fechatomaBiopsiaSenoBACAFGenero = 1;}
			if (is_null($request->fechaResultadoBiopsiaSenoGenero) || $request->fechaResultadoBiopsiaSenoGenero == false) {$reglasValidacion->fechaResultadoBiopsiaSenoGenero = 0;} else { $reglasValidacion->fechaResultadoBiopsiaSenoGenero = 1;}
			if (is_null($request->fechaResultadoBiopsiaSenoResultado) || $request->fechaResultadoBiopsiaSenoResultado == false) {$reglasValidacion->fechaResultadoBiopsiaSenoResultado = 0;} else { $reglasValidacion->fechaResultadoBiopsiaSenoResultado = 1;}
			if (is_null($request->fechaResultadoBiopsiaSenoMayorFechaTomaTest) || $request->fechaResultadoBiopsiaSenoMayorFechaTomaTest == false) {$reglasValidacion->fechaResultadoBiopsiaSenoMayorFechaTomaTest = 0;} else { $reglasValidacion->fechaResultadoBiopsiaSenoMayorFechaTomaTest = 1;}
			if (is_null($request->fResultadoBiopsiaSenoGenero) || $request->fResultadoBiopsiaSenoGenero == false) {$reglasValidacion->fResultadoBiopsiaSenoGenero = 0;} else { $reglasValidacion->fResultadoBiopsiaSenoGenero = 1;}
			if (is_null($request->resultadoBiopsiaSenoResultadoTest) || $request->resultadoBiopsiaSenoResultadoTest == false) {$reglasValidacion->resultadoBiopsiaSenoResultadoTest = 0;} else { $reglasValidacion->resultadoBiopsiaSenoResultadoTest = 1;}
			if (is_null($request->codigoIpsTomaBiopsiaSenoDB) || $request->codigoIpsTomaBiopsiaSenoDB == false) {$reglasValidacion->codigoIpsTomaBiopsiaSenoDB = 0;} else { $reglasValidacion->codigoIpsTomaBiopsiaSenoDB = 1;}
			if (is_null($request->codigoIpsTomaBiopsiaSenoGenero) || $request->codigoIpsTomaBiopsiaSenoGenero == false) {$reglasValidacion->codigoIpsTomaBiopsiaSenoGenero = 0;} else { $reglasValidacion->codigoIpsTomaBiopsiaSenoGenero = 1;}
			if (is_null($request->codigoIpsTomaBiopsiaSenoResultadoTomaTest) || $request->codigoIpsTomaBiopsiaSenoResultadoTomaTest == false) {$reglasValidacion->codigoIpsTomaBiopsiaSenoResultadoTomaTest = 0;} else { $reglasValidacion->codigoIpsTomaBiopsiaSenoResultadoTomaTest = 1;}
			if (is_null($request->hemoglobina) || $request->hemoglobina == false) {$reglasValidacion->hemoglobina = 0;} else { $reglasValidacion->hemoglobina = 1;}
			if (is_null($request->fechaCreatininaCreatinina) || $request->fechaCreatininaCreatinina == false) {$reglasValidacion->fechaCreatininaCreatinina = 0;} else { $reglasValidacion->fechaCreatininaCreatinina = 1;}
			if (is_null($request->creatinina) || $request->creatinina == false) {$reglasValidacion->creatinina = 0;} else { $reglasValidacion->creatinina = 1;}
			if (is_null($request->creatininaFechaCreatinina) || $request->creatininaFechaCreatinina == false) {$reglasValidacion->creatininaFechaCreatinina = 0;} else { $reglasValidacion->creatininaFechaCreatinina = 1;}
			if (is_null($request->hemoglobinaGlicosilada) || $request->hemoglobinaGlicosilada == false) {$reglasValidacion->hemoglobinaGlicosilada = 0;} else { $reglasValidacion->hemoglobinaGlicosilada = 1;}
			if (is_null($request->fechaHemoglobinaGlicosilada) || $request->fechaHemoglobinaGlicosilada == false) {$reglasValidacion->fechaHemoglobinaGlicosilada = 0;} else { $reglasValidacion->fechaHemoglobinaGlicosilada = 1;}
			if (is_null($request->hemoglobinaGlicosiladaFechaHemoglobinaGlicosilada) || $request->hemoglobinaGlicosiladaFechaHemoglobinaGlicosilada == false) {$reglasValidacion->hemoglobinaGlicosiladaFechaHemoglobinaGlicosilada = 0;} else { $reglasValidacion->hemoglobinaGlicosiladaFechaHemoglobinaGlicosilada = 1;}
			if (is_null($request->fechaTomaBaciloscopiaDiagnosticoResultadoTest) || $request->fechaTomaBaciloscopiaDiagnosticoResultadoTest == false) {$reglasValidacion->fechaTomaBaciloscopiaDiagnosticoResultadoTest = 0;} else { $reglasValidacion->fechaTomaBaciloscopiaDiagnosticoResultadoTest = 1;}
			if (is_null($request->resultadoBaciloscopiaDiagnosticoFechaTest) || $request->resultadoBaciloscopiaDiagnosticoFechaTest == false) {$reglasValidacion->resultadoBaciloscopiaDiagnosticoFechaTest = 0;} else { $reglasValidacion->resultadoBaciloscopiaDiagnosticoFechaTest = 1;}
			if (is_null($request->tratamientoParaHipotiroidismoCongenitoHipotiroidismo) || $request->tratamientoParaHipotiroidismoCongenitoHipotiroidismo == false) {$reglasValidacion->tratamientoParaHipotiroidismoCongenitoHipotiroidismo = 0;} else { $reglasValidacion->tratamientoParaHipotiroidismoCongenitoHipotiroidismo = 1;}
			if (is_null($request->tratamientoSifilisGestacionalGenero) || $request->tratamientoSifilisGestacionalGenero == false) {$reglasValidacion->tratamientoSifilisGestacionalGenero = 0;} else { $reglasValidacion->tratamientoSifilisGestacionalGenero = 1;}
			if (is_null($request->tratamientoSifilisGestacionalGestacion) || $request->tratamientoSifilisGestacionalGestacion == false) {$reglasValidacion->tratamientoSifilisGestacionalGestacion = 0;} else { $reglasValidacion->tratamientoSifilisGestacionalGestacion = 1;}
			if (is_null($request->tratamientoSifilisGestacionalCongenitaOGestacional) || $request->tratamientoSifilisGestacionalCongenitaOGestacional == false) {$reglasValidacion->tratamientoSifilisGestacionalCongenitaOGestacional = 0;} else { $reglasValidacion->tratamientoSifilisGestacionalCongenitaOGestacional = 1;}
			if (is_null($request->tratamientoSifilisGestacionalEdad) || $request->tratamientoSifilisGestacionalEdad == false) {$reglasValidacion->tratamientoSifilisGestacionalEdad = 0;} else { $reglasValidacion->tratamientoSifilisGestacionalEdad = 1;}
			if (is_null($request->tratamientoSifilisCongenitaGestacionalCongenita) || $request->tratamientoSifilisCongenitaGestacionalCongenita == false) {$reglasValidacion->tratamientoSifilisCongenitaGestacionalCongenita = 0;} else { $reglasValidacion->tratamientoSifilisCongenitaGestacionalCongenita = 1;}
			if (is_null($request->codigoIpsTomaCitologiaCervicoUterinaDB) || $request->codigoIpsTomaCitologiaCervicoUterinaDB == false) {$reglasValidacion->codigoIpsTomaCitologiaCervicoUterinaDB = 0;} else { $reglasValidacion->codigoIpsTomaCitologiaCervicoUterinaDB = 1;}
			$reglasValidacion->save();
			$reglasValidacionArray = new ReglasValidacion4505($reglasValidacion);
			return response()->json([
				"state" => "save",
				"reglas" => $reglasValidacionArray->getReglasArray(),
			]);
		} catch (\Exception $e) {
			return response()->json([
				"message" => "Error en el servidor",
				"error" => $e->getMessage(),
				"trace" => $e->getTrace(),
			]);
		}
	}

	public function show($id) {}

	public function update(Request $request, $id) {}

	public function destroy($id) {}
}
