<?php

namespace App\Models\Aseguramiento\Procesos;

use App\User;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class AsS1vid extends Model
{

    protected $fillable = ['fechaProceso', 'nombreArchivo', 'ruta_archivo', 'gs_usuario_id', 'fS'];

    public function usuario () {
        return $this->belongsTo(User::class,'gs_usuario_id');
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        AsS1vid::creating(function ($table){
            if(Auth::user()){
                $table->gs_usuario_id = Auth::user()->id;
            }
        });

    }

}
