<?php

namespace App\Models\Aseguramiento;

use App\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Jedrzej\Pimpable\PimpableTrait;
use OwenIt\Auditing\Contracts\Auditable;

class AsCargasRecaudo extends Model implements Auditable
{
    use \OwenIt\Auditing\Auditable;
    use PimpableTrait;

    protected $fillable = ['numero_archivos_zip','nombre_archivos_zip','numero_archivos_txt','estado_carga','gs_usuario_id'];
    protected $searchable = [];
    protected $appends = ['archivos_zip'];

    public function usuario () {
        return $this->belongsTo(User::class,'gs_usuario_id');
    }

    public function getArchivosZipAttribute($key)
    {
       return json_decode($this->attributes['nombre_archivos_zip']);
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        AsCargasRecaudo::creating(function ($table){
            if(Auth::user()){
                $table->gs_usuario_id  = Auth::user()->id;
            }
        });

    }
}
