<?php

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateAuEspecialidadsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('au_especialidads', function (Blueprint $table) {
            $table->increments('id');
            $table->string('descripcion');
            $table->char('nivel',1);
            $table->char('codHab',3);
            $table->char('codHabHos',3);
            $table->char('ind',1);
        });
        $refespecialidad = array(
            array(
                "descripcion" => "Anestesia",
                "nivel" => "3",
                "codHab" => "301",
                "codHabHos" => "301",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Anestesia- cardiovascular",
                "nivel" => "3",
                "codHab" => "303",
                "codHabHos" => "303",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Cardiologia",
                "nivel" => "3",
                "codHab" => "302",
                "codHabHos" => "302",
                "ind" => "",
            ),
            array(
                "descripcion" => "Cardiologia - electrofisiologia",
                "nivel" => "3",
                "codHab" => "302",
                "codHabHos" => "302",
                "ind" => "",
            ),
            array(
                "descripcion" => "Cardiologia - hemodinamia",
                "nivel" => "3",
                "codHab" => "302",
                "codHabHos" => "302",
                "ind" => "",
            ),
            array(
                "descripcion" => "Cardiologia pediatrica",
                "nivel" => "4",
                "codHab" => "361",
                "codHabHos" => "361",
                "ind" => "",
            ),
            array(
                "descripcion" => "Cirugia cardiovascular",
                "nivel" => "3",
                "codHab" => "303",
                "codHabHos" => "202",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Cirugia cardiovascular pediatrica",
                "nivel" => "3",
                "codHab" => "361",
                "codHabHos" => "361",
                "ind" => "",
            ),
            array(
                "descripcion" => "Cirugia de cabeza y cuello",
                "nivel" => "3",
                "codHab" => "362",
                "codHabHos" => "201",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Cirugia de cabeza y cuello oncologica",
                "nivel" => "3",
                "codHab" => "362",
                "codHabHos" => "201",
                "ind" => "",
            ),
            array(
                "descripcion" => "Otros",
                "nivel" => "2",
                "codHab" => "",
                "codHabHos" => "",
                "ind" => "",
            ),
            array(
                "descripcion" => "Cirugia de seno",
                "nivel" => "3",
                "codHab" => "364",
                "codHabHos" => "232",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Cirugia gastrointestinal y hepatobiliar",
                "nivel" => "3",
                "codHab" => "367",
                "codHabHos" => "235",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Cirugia gastrointestinal y hepatobiliar pediatrica",
                "nivel" => "3",
                "codHab" => "367",
                "codHabHos" => "235",
                "ind" => "",
            ),
            array(
                "descripcion" => "Cirugia General",
                "nivel" => "2",
                "codHab" => "304",
                "codHabHos" => "203",
                "ind" => "",
            ),
            array(
                "descripcion" => "Cirugia ginecologica",
                "nivel" => "3",
                "codHab" => "368",
                "codHabHos" => "204",
                "ind" => "",
            ),
            array(
                "descripcion" => "Cirugia Maxilofacial",
                "nivel" => "3",
                "codHab" => "411",
                "codHabHos" => "205",
                "ind" => "",
            ),
            array(
                "descripcion" => "Cirugia neurologica",
                "nivel" => "3",
                "codHab" => "305",
                "codHabHos" => "206",
                "ind" => "",
            ),
            array(
                "descripcion" => "Cirugia oftalmologica",
                "nivel" => "3",
                "codHab" => "335",
                "codHabHos" => "208",
                "ind" => "",
            ),
            array(
                "descripcion" => "Cirugia oncologica",
                "nivel" => "3",
                "codHab" => "373",
                "codHabHos" => "210",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Cirugia oral",
                "nivel" => "3",
                "codHab" => "410",
                "codHabHos" => "211",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Cirugia ortopedica",
                "nivel" => "3",
                "codHab" => "339",
                "codHabHos" => "207",
                "ind" => "",
            ),
            array(
                "descripcion" => "Cirugia otorrinolaringologia",
                "nivel" => "3",
                "codHab" => "340",
                "codHabHos" => "209",
                "ind" => "",
            ),
            array(
                "descripcion" => "Cirugia Pediatrica",
                "nivel" => "3",
                "codHab" => "306",
                "codHabHos" => "212",
                "ind" => "",
            ),
            array(
                "descripcion" => "Cirugia pediatrica oncologica",
                "nivel" => "3",
                "codHab" => "374",
                "codHabHos" => "227",
                "ind" => "",
            ),
            array(
                "descripcion" => "Cirugia Plastica",
                "nivel" => "3",
                "codHab" => "307",
                "codHabHos" => "213",
                "ind" => "",
            ),
            array(
                "descripcion" => "Cirugia terapia endovascular",
                "nivel" => "3",
                "codHab" => "218",
                "codHabHos" => "218",
                "ind" => "",
            ),
            array(
                "descripcion" => "Cirugia urologica",
                "nivel" => "3",
                "codHab" => "355",
                "codHabHos" => "215",
                "ind" => "",
            ),
            array(
                "descripcion" => "Cirugia vascular periferica",
                "nivel" => "3",
                "codHab" => "372",
                "codHabHos" => "214",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Cirugia vascular y angiolofica",
                "nivel" => "3",
                "codHab" => "372",
                "codHabHos" => "214",
                "ind" => "",
            ),
            array(
                "descripcion" => "Coloproctologia",
                "nivel" => "3",
                "codHab" => "377",
                "codHabHos" => "377",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Dermatologia",
                "nivel" => "3",
                "codHab" => "365",
                "codHabHos" => "233",
                "ind" => "",
            ),
            array(
                "descripcion" => "Dermatologia oncologia",
                "nivel" => "3",
                "codHab" => "375",
                "codHabHos" => "233",
                "ind" => "",
            ),
            array(
                "descripcion" => "Dolor y cuidados paliativos",
                "nivel" => "3",
                "codHab" => "309",
                "codHabHos" => "309",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Electrofisiologia",
                "nivel" => "3",
                "codHab" => "378",
                "codHabHos" => "378",
                "ind" => "",
            ),
            array(
                "descripcion" => "Endocrinologia",
                "nivel" => "3",
                "codHab" => "310",
                "codHabHos" => "310",
                "ind" => "",
            ),
            array(
                "descripcion" => "Endocrinologia oncologica",
                "nivel" => "3",
                "codHab" => "310",
                "codHabHos" => "310",
                "ind" => "",
            ),
            array(
                "descripcion" => "Endocrinologia pediatrica",
                "nivel" => "3",
                "codHab" => "310",
                "codHabHos" => "310",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Endodoncia",
                "nivel" => "3",
                "codHab" => "311",
                "codHabHos" => "311",
                "ind" => "",
            ),
            array(
                "descripcion" => "Enfermeria",
                "nivel" => "3",
                "codHab" => "312",
                "codHabHos" => "312",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Estomatologia",
                "nivel" => "3",
                "codHab" => "313",
                "codHabHos" => "313",
                "ind" => "",
            ),
            array(
                "descripcion" => "Fisiatria",
                "nivel" => "3",
                "codHab" => "739",
                "codHabHos" => "739",
                "ind" => "",
            ),
            array(
                "descripcion" => "Fisioterapia",
                "nivel" => "3",
                "codHab" => "739",
                "codHabHos" => "739",
                "ind" => "",
            ),
            array(
                "descripcion" => "Foniatria",
                "nivel" => "3",
                "codHab" => "740",
                "codHabHos" => "740",
                "ind" => "",
            ),
            array(
                "descripcion" => "Fonoaudiologia",
                "nivel" => "3",
                "codHab" => "740",
                "codHabHos" => "740",
                "ind" => "",
            ),
            array(
                "descripcion" => "Gastroenterologia",
                "nivel" => "3",
                "codHab" => "316",
                "codHabHos" => "235",
                "ind" => "",
            ),
            array(
                "descripcion" => "Gastroenterologia oncologica",
                "nivel" => "3",
                "codHab" => "316",
                "codHabHos" => "235",
                "ind" => "",
            ),
            array(
                "descripcion" => "Gastroenterologia pediatrica",
                "nivel" => "3",
                "codHab" => "316",
                "codHabHos" => "235",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Genetica",
                "nivel" => "3",
                "codHab" => "317",
                "codHabHos" => "317",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Geriatria",
                "nivel" => "3",
                "codHab" => "318",
                "codHabHos" => "318",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Gerontologia",
                "nivel" => "3",
                "codHab" => "319",
                "codHabHos" => "319",
                "ind" => "",
            ),
            array(
                "descripcion" => "Ginecologia y Obstetricia",
                "nivel" => "2",
                "codHab" => "320",
                "codHabHos" => "907",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Ginecologia oncologia",
                "nivel" => "3",
                "codHab" => "379",
                "codHabHos" => "204",
                "ind" => "",
            ),
            array(
                "descripcion" => "Hematologia",
                "nivel" => "3",
                "codHab" => "321",
                "codHabHos" => "321",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Hematologia pediatrica",
                "nivel" => "3",
                "codHab" => "391",
                "codHabHos" => "391",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Hepatologia",
                "nivel" => "3",
                "codHab" => "316",
                "codHabHos" => "235",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Hepatologia pediatrica",
                "nivel" => "3",
                "codHab" => "316",
                "codHabHos" => "235",
                "ind" => "",
            ),
            array(
                "descripcion" => "Implantologia",
                "nivel" => "3",
                "codHab" => "322",
                "codHabHos" => "226",
                "ind" => "",
            ),
            array(
                "descripcion" => "Infectologia",
                "nivel" => "3",
                "codHab" => "323",
                "codHabHos" => "323",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Infectologia pediatrica",
                "nivel" => "3",
                "codHab" => "323",
                "codHabHos" => "323",
                "ind" => "",
            ),
            array(
                "descripcion" => "Inmunologia",
                "nivel" => "3",
                "codHab" => "324",
                "codHabHos" => "324",
                "ind" => "",
            ),
            array(
                "descripcion" => "Mastologia",
                "nivel" => "3",
                "codHab" => "364",
                "codHabHos" => "232",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Medicina familiar",
                "nivel" => "3",
                "codHab" => "325",
                "codHabHos" => "325",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Medicina fisica y del deporte",
                "nivel" => "3",
                "codHab" => "326",
                "codHabHos" => "326",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Medicina fisica y rehabilitacion",
                "nivel" => "3",
                "codHab" => "327",
                "codHabHos" => "327",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Medicina general",
                "nivel" => "1",
                "codHab" => "328",
                "codHabHos" => "328",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Medicina interna",
                "nivel" => "2",
                "codHab" => "329",
                "codHabHos" => "329",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Medicina nuclear",
                "nivel" => "3",
                "codHab" => "383",
                "codHabHos" => "383",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Nefrologia",
                "nivel" => "3",
                "codHab" => "330",
                "codHabHos" => "330",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Nefrologia pediatrica",
                "nivel" => "3",
                "codHab" => "384",
                "codHabHos" => "384",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Neonatologia",
                "nivel" => "3",
                "codHab" => "385",
                "codHabHos" => "385",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Neumologia",
                "nivel" => "3",
                "codHab" => "331",
                "codHabHos" => "331",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Neumologia oncologica",
                "nivel" => "3",
                "codHab" => "331",
                "codHabHos" => "331",
                "ind" => "",
            ),
            array(
                "descripcion" => "Neumologia pediatrica",
                "nivel" => "3",
                "codHab" => "386",
                "codHabHos" => "386",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Neurocirugía",
                "nivel" => "3",
                "codHab" => "387",
                "codHabHos" => "206",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Neurocirugia oncologica",
                "nivel" => "3",
                "codHab" => "387",
                "codHabHos" => "206",
                "ind" => "",
            ),
            array(
                "descripcion" => "Neurologia",
                "nivel" => "3",
                "codHab" => "332",
                "codHabHos" => "206",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Neurologia pediatrica",
                "nivel" => "3",
                "codHab" => "388",
                "codHabHos" => "206",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Neurosicologia",
                "nivel" => "2",
                "codHab" => "344",
                "codHabHos" => "344",
                "ind" => "",
            ),
            array(
                "descripcion" => "Neurosiquiatria",
                "nivel" => "3",
                "codHab" => "345",
                "codHabHos" => "345",
                "ind" => "",
            ),
            array(
                "descripcion" => "Nutricion y dietetica",
                "nivel" => "3",
                "codHab" => "333",
                "codHabHos" => "333",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Odontologia Especializada",
                "nivel" => "3",
                "codHab" => "334",
                "codHabHos" => "334",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Odontologia General",
                "nivel" => "1",
                "codHab" => "334",
                "codHabHos" => "334",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Odontologia oncologica",
                "nivel" => "3",
                "codHab" => "334",
                "codHabHos" => "334",
                "ind" => "",
            ),
            array(
                "descripcion" => "Odontopediatria",
                "nivel" => "3",
                "codHab" => "396",
                "codHabHos" => "396",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Oftalmologia",
                "nivel" => "2",
                "codHab" => "335",
                "codHabHos" => "208",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Oftalmologia - cornea",
                "nivel" => "3",
                "codHab" => "335",
                "codHabHos" => "208",
                "ind" => "",
            ),
            array(
                "descripcion" => "Oftalmologia glaucomatologo",
                "nivel" => "3",
                "codHab" => "335",
                "codHabHos" => "208",
                "ind" => "",
            ),
            array(
                "descripcion" => "Oftalmologia iridologo",
                "nivel" => "3",
                "codHab" => "335",
                "codHabHos" => "208",
                "ind" => "",
            ),
            array(
                "descripcion" => "Oftalmologia oncologica",
                "nivel" => "3",
                "codHab" => "390",
                "codHabHos" => "208",
                "ind" => "",
            ),
            array(
                "descripcion" => "Oftalmologia pediatrica",
                "nivel" => "3",
                "codHab" => "335",
                "codHabHos" => "208",
                "ind" => "",
            ),
            array(
                "descripcion" => "Oftalmologia plastica",
                "nivel" => "3",
                "codHab" => "335",
                "codHabHos" => "208",
                "ind" => "",
            ),
            array(
                "descripcion" => "Oftalmologia retinologo",
                "nivel" => "3",
                "codHab" => "335",
                "codHabHos" => "208",
                "ind" => "",
            ),
            array(
                "descripcion" => "Oncologia clinica",
                "nivel" => "3",
                "codHab" => "709",
                "codHabHos" => "210",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Oncologia pediatrica",
                "nivel" => "3",
                "codHab" => "374",
                "codHabHos" => "227",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Optometria",
                "nivel" => "3",
                "codHab" => "337",
                "codHabHos" => "337",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Ortodoncia",
                "nivel" => "3",
                "codHab" => "338",
                "codHabHos" => "338",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Ortopedia y traumatologia",
                "nivel" => "2",
                "codHab" => "339",
                "codHabHos" => "207",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Ortopedia oncologica",
                "nivel" => "3",
                "codHab" => "393",
                "codHabHos" => "207",
                "ind" => "",
            ),
            array(
                "descripcion" => "Ortopedia Pediatrica",
                "nivel" => "3",
                "codHab" => "392",
                "codHabHos" => "207",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Otorrinolaringologia",
                "nivel" => "3",
                "codHab" => "340",
                "codHabHos" => "209",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Otras consultas (subespecialidades)",
                "nivel" => "3",
                "codHab" => "356",
                "codHabHos" => "356",
                "ind" => "",
            ),
            array(
                "descripcion" => "Patologia",
                "nivel" => "3",
                "codHab" => "341",
                "codHabHos" => "341",
                "ind" => "",
            ),
            array(
                "descripcion" => "Pediatria",
                "nivel" => "2",
                "codHab" => "342",
                "codHabHos" => "212",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Perinatologia",
                "nivel" => "3",
                "codHab" => "320",
                "codHabHos" => "320",
                "ind" => "",
            ),
            array(
                "descripcion" => "Periodoncia",
                "nivel" => "3",
                "codHab" => "343",
                "codHabHos" => "343",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Psicologia",
                "nivel" => "2",
                "codHab" => "344",
                "codHabHos" => "344",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Psiquiatria",
                "nivel" => "3",
                "codHab" => "345",
                "codHabHos" => "103",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Radiologia e Imagenes Diagnosticas",
                "nivel" => "3",
                "codHab" => "710",
                "codHabHos" => "710",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Radiologia - diagnostica e intervencionista",
                "nivel" => "3",
                "codHab" => "710",
                "codHabHos" => "710",
                "ind" => "",
            ),
            array(
                "descripcion" => "Radioterapia oncologica - Quimioterapia",
                "nivel" => "3",
                "codHab" => "711",
                "codHabHos" => "711",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Rehabilitacion oncologica",
                "nivel" => "3",
                "codHab" => "346",
                "codHabHos" => "346",
                "ind" => "",
            ),
            array(
                "descripcion" => "Rehabilitacion oral",
                "nivel" => "3",
                "codHab" => "347",
                "codHabHos" => "347",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Reumatologia",
                "nivel" => "3",
                "codHab" => "348",
                "codHabHos" => "348",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Salud ocupacional",
                "nivel" => "1",
                "codHab" => "349",
                "codHabHos" => "349",
                "ind" => "",
            ),
            array(
                "descripcion" => "Psiquiatria Pediatrica",
                "nivel" => "3",
                "codHab" => "345",
                "codHabHos" => "103",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Terapia alternativa",
                "nivel" => "3",
                "codHab" => "350",
                "codHabHos" => "350",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Terapia del lenguaje",
                "nivel" => "3",
                "codHab" => "351",
                "codHabHos" => "351",
                "ind" => "",
            ),
            array(
                "descripcion" => "Terapia ocupacional",
                "nivel" => "3",
                "codHab" => "352",
                "codHabHos" => "352",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Terapia respiratoria",
                "nivel" => "3",
                "codHab" => "353",
                "codHabHos" => "353",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Toxicologia",
                "nivel" => "3",
                "codHab" => "354",
                "codHabHos" => "354",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Transplante",
                "nivel" => "3",
                "codHab" => "216",
                "codHabHos" => "216",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Trasplante hepatico adulto",
                "nivel" => "3",
                "codHab" => "221",
                "codHabHos" => "221",
                "ind" => "",
            ),
            array(
                "descripcion" => "Trasplante hepatico pediatrico",
                "nivel" => "3",
                "codHab" => "221",
                "codHabHos" => "221",
                "ind" => "",
            ),
            array(
                "descripcion" => "Urologia",
                "nivel" => "3",
                "codHab" => "355",
                "codHabHos" => "215",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Urologia oncologica",
                "nivel" => "3",
                "codHab" => "395",
                "codHabHos" => "215",
                "ind" => "",
            ),
            array(
                "descripcion" => "Urologia pediatrica",
                "nivel" => "3",
                "codHab" => "355",
                "codHabHos" => "215",
                "ind" => "",
            ),
            array(
                "descripcion" => "Ginecologia",
                "nivel" => "2",
                "codHab" => "368",
                "codHabHos" => "204",
                "ind" => "",
            ),
            array(
                "descripcion" => "Ortoptica",
                "nivel" => "2",
                "codHab" => "335",
                "codHabHos" => "208",
                "ind" => "",
            ),
            array(
                "descripcion" => "Alergología",
                "nivel" => "3",
                "codHab" => "324",
                "codHabHos" => "324",
                "ind" => "",
            ),
            array(
                "descripcion" => "Cirugía articular",
                "nivel" => "3",
                "codHab" => "339",
                "codHabHos" => "207",
                "ind" => "",
            ),
            array(
                "descripcion" => "Cirugía ocular",
                "nivel" => "3",
                "codHab" => "335",
                "codHabHos" => "208",
                "ind" => "",
            ),
            array(
                "descripcion" => "Cirugia de torax",
                "nivel" => "3",
                "codHab" => "366",
                "codHabHos" => "234",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Medicina del Dolor (Algologia)",
                "nivel" => "3",
                "codHab" => "309",
                "codHabHos" => "309",
                "ind" => "",
            ),
            array(
                "descripcion" => "N/A",
                "nivel" => "4",
                "codHab" => "328",
                "codHabHos" => "328",
                "ind" => "",
            ),
            array(
                "descripcion" => "Trabajo Social",
                "nivel" => "1",
                "codHab" => "",
                "codHabHos" => "",
                "ind" => "",
            ),
            array(
                "descripcion" => "Equipo interdisciplinario",
                "nivel" => "3",
                "codHab" => "",
                "codHabHos" => "",
                "ind" => "",
            ),
            array(
                "descripcion" => "Estomatologia y cirugia oral",
                "nivel" => "3",
                "codHab" => "211",
                "codHabHos" => "410",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Radiologia oral y maxilofacial",
                "nivel" => "3",
                "codHab" => "724",
                "codHabHos" => "724",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Medicina Aerospacial",
                "nivel" => "3",
                "codHab" => "",
                "codHabHos" => "",
                "ind" => "",
            ),
            array(
                "descripcion" => "Medicina alternativa (ayurveda)",
                "nivel" => "3",
                "codHab" => "350",
                "codHabHos" => "350",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Medicina alternativa (homeopatia)",
                "nivel" => "3",
                "codHab" => "398",
                "codHabHos" => "398",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Medicina alternativa (medicina tradicional china)",
                "nivel" => "3",
                "codHab" => "400",
                "codHabHos" => "400",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Medicina alternativa (naturopatia)",
                "nivel" => "3",
                "codHab" => "404",
                "codHabHos" => "404",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Medicina del trabajo",
                "nivel" => "3",
                "codHab" => "407",
                "codHabHos" => "407",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Medicina forense",
                "nivel" => "3",
                "codHab" => "",
                "codHabHos" => "",
                "ind" => "",
            ),
            array(
                "descripcion" => "Oncohematologia pediatrica",
                "nivel" => "3",
                "codHab" => "391",
                "codHabHos" => "391",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Reumatologia pediatrica",
                "nivel" => "3",
                "codHab" => "348",
                "codHabHos" => "348",
                "ind" => "1",
            ),
            array(
                "descripcion" => "Sexología clínica ",
                "nivel" => "3",
                "codHab" => "",
                "codHabHos" => "",
                "ind" => "",
            ),
            array(
                "descripcion" => "Cirugia Vascular",
                "nivel" => "4",
                "codHab" => "303",
                "codHabHos" => "202",
                "ind" => "",
            ),
            array(
                "descripcion" => "Otologia",
                "nivel" => "2",
                "codHab" => "",
                "codHabHos" => "",
                "ind" => "",
            ),
            array(
                "descripcion" => "Retinologia Pediatrica",
                "nivel" => "3",
                "codHab" => "335",
                "codHabHos" => "208",
                "ind" => "",
            ),
            array(
                "descripcion" => "Estrabologo Neurologo",
                "nivel" => "3",
                "codHab" => "",
                "codHabHos" => "",
                "ind" => "",
            ),
            array(
                "descripcion" => "Oftamologo Esp en Orbita",
                "nivel" => "3",
                "codHab" => "335",
                "codHabHos" => "208",
                "ind" => "",
            ),
        );

        DB::table('au_especialidads')->insert($refespecialidad);

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('au_especialidads');
    }
}
