<?php

namespace App\Models\CentroRegulador;

use App\Models\RedServicios\RsEntidade;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Jedrzej\Pimpable\PimpableTrait;
use OwenIt\Auditing\Contracts\Auditable;

class AuReftraslado extends Model implements Auditable
{
    use \OwenIt\Auditing\Auditable;
    use PimpableTrait;
    protected $fillable = [
        'au_referencia_id',
        'contacto',
        'entidad_destino_id',
        'entidad_origen_id',
        'entidad_transporta_id',
        'fecha_llegada',
        'estado',
        'fecha_solicitud',
        'fecha_traslado',
        'tipo_ambulancia',
        'tipo_traslado',
        'gs_usuario_id'
   ];
    protected $hidden = ['created_at','updated_at'];

    public function referencia () {
        return $this->belongsTo(AuReferencia::class, 'au_referencia_id');
    }

    public function entidadOrigen () {
        return $this->belongsTo(RsEntidade::class, 'entidad_origen_id');
    }

    public function entidadDestino () {
        return $this->belongsTo(RsEntidade::class,'entidad_destino_id');
    }

    public function entidadTransportadora () {
        return $this->belongsTo(RsEntidade::class, 'entidad_transporta_id');
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        AuReftraslado::creating(function ($table){
            if(Auth::user()){
                $table->gs_usuario_id  = Auth::user()->id;
            }
        });

    }
}
