<?php

namespace App\Models\CentroRegulador;

use App\Models\General\GnArchivo;
use App\User;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use OwenIt\Auditing\Contracts\Auditable;

class AuRefbitacora extends Model implements Auditable
{
    use \OwenIt\Auditing\Auditable;

    protected $fillable = [
        'au_referencia_id',
        'fecha',
        'observaciones',
        'gs_usuario_id',
        'au_refpresentacion_id',
        'au_reftraslado_id',
        'au_tipaccion_id',
        'gn_archivo_id'
    ];

    protected $appends = ['timeline_fecha'];

    public function archivo ()
    {
        return $this->belongsTo(GnArchivo::class, 'gn_archivo_id');
    }

    public function referencia () {
        return $this->belongsTo(AuReferencia::class,'au_referencia_id');
    }

    public function presentacion () {
        return $this->belongsTo(AuRefpresentacione::class, 'au_refpresentacion_id');
    }

    public function traslado () {
        return $this->belongsTo(AuReftraslado::class,'au_reftraslado_id');
    }

    public function accion () {
        return $this->belongsTo(AuReftipaccione::class, 'au_tipaccion_id');
    }

    public function getTimelineFechaAttribute () {
        $datetime = Carbon::parse($this->attributes['created_at']);
        setlocale(LC_ALL, "es_ES");
//        setlocale(LC_TIME, 'es');
        return $datetime->formatLocalized('%e de %B %Y');          // Mittwoch 21 Mai 1975
//        $datetime = Carbon::parse($this->attributes['fecha'])->toDateTimeString()->locale('es')->diffForHumans();
//        return $datetime;
    }

    public function usuario(){
        return $this->belongsTo(User::class, 'gs_usuario_id');
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        AuRefbitacora::creating(function ($table){
            if(Auth::user()){
                $table->gs_usuario_id  = Auth::user()->id;
            }
        });

    }

}
